In [ ]:
!pip -q install bitsandbytes accelerate
!pip -q install langchain
!pip install einops
!pip install --upgrade --quiet  langchain-community qdrant-client
!pip install langchainhub
!pip install -U langchain-huggingface
!pip -q install PyMuPDF tqdm aiolimiter faiss-cpu PyPDF2 pdfplumber rouge-score bert-score evaluate
!pip install -U --quiet "sentence-transformers==5.0.0"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.9/72.9 MB 34.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 113.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 97.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 53.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 11.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 42.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 19.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 105.9 MB/s eta 0:00:00
Requirement already satisfied: einops in /usr/local/lib/python3.11/dist-packages (0.8.1)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 88.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 337.3/337.3 kB 25.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.2/45.2 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 3.9 MB/s eta 0:00:00
Collecting langchainhub
  Downloading langchainhub-0.1.21-py3-none-any.whl.metadata (659 bytes)
Collecting packaging<25,>=23.2 (from langchainhub)
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.11/dist-packages (from langchainhub) (2.32.3)
Collecting types-requests<3.0.0.0,>=2.31.0.2 (from langchainhub)
  Downloading types_requests-2.32.4.20250611-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchainhub) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchainhub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchainhub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchainhub) (2025.7.14)
Downloading langchainhub-0.1.21-py3-none-any.whl (5.2 kB)
Downloading packaging-24.2-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 6.2 MB/s eta 0:00:00
Downloading types_requests-2.32.4.20250611-py3-none-any.whl (20 kB)
Installing collected packages: types-requests, packaging, langchainhub
  Attempting uninstall: packaging
    Found existing installation: packaging 25.0
    Uninstalling packaging-25.0:
      Successfully uninstalled packaging-25.0
Successfully installed langchainhub-0.1.21 packaging-24.2 types-requests-2.32.4.20250611

Collecting langchain-huggingface
  Downloading langchain_huggingface-0.3.1-py3-none-any.whl.metadata (996 bytes)
Requirement already satisfied: langchain-core<1.0.0,>=0.3.70 in /usr/local/lib/python3.11/dist-packages (from langchain-huggingface) (0.3.72)
Requirement already satisfied: tokenizers>=0.19.1 in /usr/local/lib/python3.11/dist-packages (from langchain-huggingface) (0.21.2)
Requirement already satisfied: huggingface-hub>=0.33.4 in /usr/local/lib/python3.11/dist-packages (from langchain-huggingface) (0.34.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.33.4->langchain-huggingface) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.33.4->langchain-huggingface) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.33.4->langchain-huggingface) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.33.4->langchain-huggingface) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.33.4->langchain-huggingface) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.33.4->langchain-huggingface) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.33.4->langchain-huggingface) (4.14.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.33.4->langchain-huggingface) (1.1.5)
Requirement already satisfied: langsmith>=0.3.45 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.70->langchain-huggingface) (0.4.8)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.70->langchain-huggingface) (8.5.0)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.70->langchain-huggingface) (1.33)
Requirement already satisfied: pydantic>=2.7.4 in /usr/local/lib/python3.11/dist-packages (from langchain-core<1.0.0,>=0.3.70->langchain-huggingface) (2.11.7)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.11/dist-packages (from jsonpatch<2.0,>=1.33->langchain-core<1.0.0,>=0.3.70->langchain-huggingface) (3.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.70->langchain-huggingface) (0.28.1)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /usr/local/lib/python3.11/dist-packages (from langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.70->langchain-huggingface) (3.11.1)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.70->langchain-huggingface) (1.0.0)
Requirement already satisfied: zstandard<0.24.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.70->langchain-huggingface) (0.23.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.7.4->langchain-core<1.0.0,>=0.3.70->langchain-huggingface) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.7.4->langchain-core<1.0.0,>=0.3.70->langchain-huggingface) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.7.4->langchain-core<1.0.0,>=0.3.70->langchain-huggingface) (0.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.33.4->langchain-huggingface) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.33.4->langchain-huggingface) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.33.4->langchain-huggingface) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.33.4->langchain-huggingface) (2025.7.14)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.70->langchain-huggingface) (4.9.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.70->langchain-huggingface) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.70->langchain-huggingface) (0.16.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx<1,>=0.23.0->langsmith>=0.3.45->langchain-core<1.0.0,>=0.3.70->langchain-huggingface) (1.3.1)
Downloading langchain_huggingface-0.3.1-py3-none-any.whl (27 kB)
Installing collected packages: langchain-huggingface
Successfully installed langchain-huggingface-0.3.1
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 kB 3.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.1/24.1 MB 55.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.3/31.3 MB 78.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 601.3 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 121.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 93.2 MB/s eta 0:00:00
  Building wheel for rouge-score (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 470.2/470.2 kB 28.3 MB/s eta 0:00:00

In [ ]:
!pip install faiss-gpu

ERROR: Could not find a version that satisfies the requirement faiss-gpu (from versions: none)
ERROR: No matching distribution found for faiss-gpu

KeyboardInterrupt:

In [ ]:
import torch
import faiss
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoModelForCausalLM
from transformers import AutoProcessor
from peft import PeftModel
import numpy as np
import pandas as pd
from typing import List, Dict, Tuple, Optional, Sequence, Union, Iterable
from rouge_score import rouge_scorer
from bert_score import score as bert_score
from datasets import load_dataset
import matplotlib.pyplot as plt
import seaborn as sns
import re
from spacy.lang.en import English
import fitz
from time import perf_counter as timer
import textwrap
from sentence_transformers import util
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import AutoProcessor, AutoModelForVision2Seq
from PIL import Image
import requests
import ast
from langchain.text_splitter import TokenTextSplitter
from transformers import MllamaForConditionalGeneration, AutoProcessor
from torch.nn.functional import normalize
import nest_asyncio
from google.colab import userdata
from aiolimiter import AsyncLimiter
import urllib.parse, pathlib
import html, unicodedata, logging
import spacy
from sentence_transformers import SentenceTransformer
from sentence_transformers import SentenceTransformer, InputExample, losses
from sentence_transformers.trainer import SentenceTransformerTrainer, SentenceTransformerTrainingArguments
from torch.utils.data import DataLoader
from transformers import EarlyStoppingCallback
from pathlib import Path
from itertools import chain
from collections import defaultdict
from concurrent.futures import ProcessPoolExecutor, as_completed
import torch.nn.functional as F
import torch.nn as nn
from datasets import Dataset as HFDataset
from tqdm.auto import tqdm
from transformers import AutoTokenizer, TrainingArguments, Trainer, set_seed, pipeline
from utils import *
import evaluate
from datasets import Dataset
import os, random, time, json, statistics, asyncio, logging, openai, tiktoken
import itertools
import gc, logging
from openai import AsyncOpenAI
from scipy.stats import ttest_rel
from IPython.display import Javascript, display
import time

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#!pip install -q --upgrade huggingface_hub
!huggingface-cli login

⚠️  Warning: 'huggingface-cli login' is deprecated. Use 'hf auth login' instead.

    _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
    _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
    _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
    _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
    _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|

    To log in, `huggingface_hub` requires a token generated from https://huggingface.co/settings/tokens .
Enter your token (input will not be visible):
Add token as git credential? (Y/n) n
Token is valid (permission: read).
The token `mids_267_token` has been saved to /root/.cache/huggingface/stored_tokens
Your token has been saved to /root/.cache/huggingface/token
Login successful.
The current active token is: `mids_267_token`

In [ ]:
pdf_paths = ['/content/drive/MyDrive/fMRIwork/rag_docs/ales.pdf']

# Doc loading and processing

In [ ]:
pages = open_and_read_pdfs(pdf_paths)

In [ ]:
for page in pages:
  page['text'] = clean_text(page['text'])
  page['text'] = split_sentences(page['text'])

In [ ]:
pages = clean_pages(pages)

In [ ]:
processed_pages = []

for page in pages:
    # fetch raw page text
    raw_text = (
        page["text"]
        if isinstance(page, dict)
        else getattr(page, "page_content", "")
    )
    if isinstance(raw_text, list):               # flatten list into single str
        raw_text = " ".join(raw_text)

    # sentence split -> clean -> token‑aligned chunks
    sentences = [
        s for s in map(clean_sentence, split_sentences(raw_text)) if s
    ]
    chunks = token_chunks(sentences, chunk_size=300, overlap=80)

    # 3) store results in metadata container
    meta = ensure_metadata_container(page)
    meta["sentences"]        = sentences
    meta["token_chunks"]     = chunks
    meta["num_token_chunks"] = len(chunks)

    processed_pages.append(page)

In [ ]:
processed_pages[0]['metadata']['sentences']

['Ann Laparosc Endosc Surg 2020;5:15 | http://dx.doi.org/10.21037/ales.2020.02.06 Introduction In the United States, gallstone disease remains a prevalent condition affecting over 20 to 25 million Americans, representing 10–15% of the population (1,2).',
 'Although not every patient with gallstones will manifest symptoms or require intervention, laparoscopic cholecystectomy (LC), which accounts for 90% of all cholecystectomies, remains one of the most commonly performed procedures— conservatively numbering 750,000 per year (3).',
 'Since its introduction in the 1980s and subsequent adoption, LC has become the standard of care due to its advantages of reduced cost and hospital length of stay, and increased patient satisfaction (4,5).',
 'Overall, LC is considered a safe procedure, as morbidity can occur in approximately 6–8% of the patients (6), including bleeding, abscess, bile leak, bowel/vascular injury, wound complication, and bile duct injury (BDI) (6,7).',
 'Although bile duct injury has been become less frequent over the years, occurring in approximately 0.2–0.4% of cases, the frequency is still somewhat higher than in the era of open cholecystectomy (8,9).',
 'Thus, performing laparoscopic cholecystectomy safely and embracing the principles outlined below is crucial.',
 'BDI has been associated with other complications and the necessity for further procedures/interventions, higher mortality, lower quality of life and disability, increased healthcare burden and litigation (10,11).',
 'Studies have shown both increased short and long-term mortality due to BDI (12).',
 'In order to enhance the safety of cholecystectomy and reduce the rate of biliary injury, in 2014 the Society of Gastrointestinal and Endoscopic Surgeons (SAGES) formed the Safe Cholecystectomy Task Force with the goal of enhancing a culture of safety around this procedure (13).',
 'The authors report the surgical techniques that follow the principles espoused by SAGES during laparoscopic cholecystectomy in order to ensure a safe procedure.',
 'Operative technique The patient is placed in supine position with the left arm tucked to facilitate intraoperative cholangiography.',
 'With the surgeon standing to the left of the patient and first assistant standing on the patient’s right side, abdominal access is obtained and pneumoperitoneum is established.',
 'In our practice, we generally perform an open cutdown technique and Hasson cannula placement at the umbilicus Surgical Technique How do I do it: laparoscopic cholecystectomy Arnab Majumder, Maria S. Altieri, L. Michael Brunt Section of Minimally Invasive Surgery, Department of Surgery, Washington University School of Medicine, St. Louis, MO, USA Correspondence to: L. Michael Brunt, MD.',
 'Department of Surgery, Washington University School of Medicine, 660 S Euclid Ave, Box 8109, St. Louis, MO 63105, USA.',
 'Email: bruntm@wustl.edu.',
 'Abstract: Laparoscopic cholecystectomy remains one of the most commonly performed procedures in the United States and across the world.',
 'Although the laparoscopic approach is considered safe, complications are still prevalent and occur in 6–8% of patients.',
 'Despite its relative infrequency, the most serious major complication is bile duct injury, which is a major source of morbidity and increased mortality.',
 'Bile duct injury can convert a potentially outpatient procedure into one requiring further operative interventions, additional cost, and a significant negative impact on the patient.',
 'We report our surgical technique emphasizing the principles of safe cholecystectomy as highlighted by the Society of American Gastrointestinal and Endoscopic Surgeons (SAGES) that are paramount during laparoscopic cholecystectomy to minimize risks and ensure a successful outcome.',
 'Keywords: Laparoscopic cholecystectomy; operative steps; technique; critical view of safety; bile duct injury Received: 02 February 2020; Accepted: 24 February 2020; Published: 20 April 2020.']

In [ ]:
enc = tiktoken.get_encoding("cl100k_base")

first_doc = processed_pages[0]

raw_text = getattr(first_doc, "page_content", None) or first_doc.get("text", "")
chunks   = first_doc['metadata']["token_chunks"]

print("── Summary ──")
print(f"Original text length : {len(raw_text):,} characters")
print(f"Number of sentences  : {len(first_doc['metadata']['sentences']):,}")
print(f"Number of chunks     : {len(chunks):,}")

sizes = [len(enc.encode(c)) for c in chunks]      # token counts
print("\nFirst few chunks:")
for i, (c, toks) in enumerate(zip(chunks, sizes)):
    if i == 5: break
    print(f"  Chunk {i:2d}: {toks:3d} tokens | {len(c):4d} chars | “{c[:80]}…”")

df = pd.DataFrame(
    {
        "chunk_id": range(len(chunks)),
        "tokens": sizes,
        "chars": [len(c) for c in chunks],
        "preview": [c[:120] + ("…" if len(c) > 120 else "") for c in chunks],
    }
)
df.head()

── Summary ──
Original text length : 21 characters
Number of sentences  : 21
Number of chunks     : 4

First few chunks:
  Chunk  0: 300 tokens | 1267 chars | “Ann Laparosc Endosc Surg 2020;5:15 | http://dx.doi.org/10.21037/ales.2020.02.06 …”
  Chunk  1: 285 tokens | 1373 chars | “ duct injury (BDI) (6,7).Although bile duct injury has been become less frequent…”
  Chunk  2: 291 tokens | 1345 chars | “ principles espoused by SAGES during laparoscopic cholecystectomy in order to en…”
  Chunk  3: 209 tokens | 1060 chars | “.Abstract: Laparoscopic cholecystectomy remains one of the most commonly perform…”

   chunk_id  tokens  chars                                            preview
0         0     300   1267  Ann Laparosc Endosc Surg 2020;5:15 | http://dx...
1         1     285   1373   duct injury (BDI) (6,7).Although bile duct in...
2         2     291   1345   principles espoused by SAGES during laparosco...
3         3     209   1060  .Abstract: Laparoscopic cholecystectomy remain...

In [ ]:
# Make sure the retriever_finetuned folder exists
retriever_path = '/content/drive/MyDrive/SurgiRAG/retriever_finetuned'
print(f"Contents of {retriever_path}:")

def explore_directory(path, max_depth=4, current_depth=0):
    if current_depth > max_depth:
        return

    if not os.path.exists(path):
        print(f"Path doesn't exist: {path}")
        return

    print("  " * current_depth + f"{os.path.basename(path)}/")

    try:
        for item in os.listdir(path):
            item_path = os.path.join(path, item)
            if os.path.isdir(item_path):
                explore_directory(item_path, max_depth, current_depth + 1)
            else:
                print("  " * (current_depth + 1) + f"{item}")
    except PermissionError:
        print("  " * (current_depth + 1) + "Permission denied")

explore_directory(retriever_path)

Contents of /content/drive/MyDrive/SurgiRAG/retriever_finetuned:
retriever_finetuned/
  outputs/
    retriever_fast/
      sentence_transformer/
        tokenizer_config.json
        tokenizer.json
        config.json
        sentence_bert_config.json
        model.safetensors
        special_tokens_map.json
        modules.json
        README.md
        vocab.txt
        config_sentence_transformers.json
        1_Pooling/
          config.json

In [ ]:
retr_model_path = "/content/drive/MyDrive/SurgiRAG/retriever_finetuned/outputs/retriever_fast/sentence_transformer"
retr_model = SentenceTransformer(retr_model_path).to("cuda")

In [ ]:
embeddings, text_chunks, chunk_meta = embed_text(processed_pages, retr_model, batch_size=64)

Total chunks: 19

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Embeddings tensor shape: torch.Size([19, 768])

In [ ]:
index_path = "indices/docs.idx"
Path(index_path).parent.mkdir(parents=True, exist_ok=True)

_ = build_index(
        embeddings,
        index_path = index_path,
        use_gpu    = False,
        hnsw_m     = None
    )

Building exact IndexFlatIP …
Index built with 19 vectors  |  dim = 768
Index saved to: indices/docs.idx

# RAG Pipline

In [ ]:
adapter_dir  = "/content/drive/MyDrive/SurgiRAG/generator_finetuned/lora-bioasq"
base_gen_model   = "meta-llama/Llama-3.2-11B-Vision-Instruct"

In [ ]:
# new (with video branch)
class RAGPipeline:
    def __init__(self,
                 retriever_model_path: str,
                 corpus_chunks: list[str],
                 faiss_index: "faiss.Index" = None,
                 faiss_index_path: str | None = None,
                 shared_retriever=None,
                 reranker_model_name: str | None = "BAAI/bge-reranker-large",
                 shared_reranker=None,
                 generator_base_model: str | None = "meta-llama/Llama-3.2-11B-Vision-Instruct",
                 generator_lora_path: str | None = None,
                 generator_object=None,
                 system_prompt: str | None = None,
                 # NEW: Video-related parameters
                 video_data_path: str | None = "/content/drive/MyDrive/SurgiRAG/surgirag_data.json",
                 video_weight: float = 0.3):  # Weight for combining text+video retrieval

        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        self.corpus = corpus_chunks
        self.video_weight = video_weight  # NEW: Balance between text and video retrieval

        # Retriever
        if shared_retriever is not None:
            self.retriever = shared_retriever
        else:
            self.retriever = SentenceTransformer(retriever_model_path)
            if torch.cuda.is_available():
                self.retriever = self.retriever.to("cuda")

        # FAISS index
        if faiss_index is not None:
            self.index = faiss_index
        elif faiss_index_path is not None:
            index = faiss.read_index(faiss_index_path)
            if torch.cuda.is_available():
                # keep on CPU to save VRAM; comment‑out if we need GPU
                # res = faiss.StandardGpuResources()
                # index = faiss.index_cpu_to_gpu(res, 0, index)
                pass
            self.index = index
        else:
            raise ValueError("Need either faiss_index or faiss_index_path")

        # Reranker
        if reranker_model_name is None:
            self.reranker_model = None
            self.reranker_tokenizer = None
        elif shared_reranker is not None:
            self.reranker_model = shared_reranker
            self.reranker_tokenizer = AutoTokenizer.from_pretrained(reranker_model_name)
        else:
            self.reranker_tokenizer = AutoTokenizer.from_pretrained(reranker_model_name)
            self.reranker_model = AutoModelForSequenceClassification.from_pretrained(
                reranker_model_name).to(self.device).eval()

        # Generator
        if generator_object is not None:
            self.generator_model = generator_object
            self.generator_tokenizer = AutoTokenizer.from_pretrained(
                generator_base_model, trust_remote_code=True)
        else:
            if generator_base_model is None:
                raise ValueError("Need generator_base_model when "
                                 "generator_object is None.")
            dtype = torch.bfloat16 if torch.cuda.is_available() else torch.float32
            self.generator_tokenizer = AutoTokenizer.from_pretrained(
                generator_base_model, trust_remote_code=True)
            base_model = AutoModelForCausalLM.from_pretrained(
                generator_base_model,
                device_map="auto",
                torch_dtype=dtype,
                trust_remote_code=True,
            )
            if generator_lora_path:
                base_model = PeftModel.from_pretrained(
                    base_model, generator_lora_path).merge_and_unload()
            self.generator_model = base_model.eval()

        # DEBUG: Check tokenizer setup
        if not hasattr(self.generator_tokenizer, 'pad_token') or self.generator_tokenizer.pad_token is None:
            self.generator_tokenizer.pad_token = self.generator_tokenizer.eos_token
            print("Set pad_token to eos_token")

        # Load video data for transcript-based retrieval
        self.video_data = None

        if video_data_path and os.path.exists(video_data_path):
            try:
                with open(video_data_path, 'r') as f:
                    self.video_data = json.load(f)

                print(f"Loaded {len(self.video_data)} video segments for transcript-based retrieval")
            except Exception as e:
                print(f"Failed to load video data: {e}")
                self.video_data = None

        # prompt
        self.system_prompt = system_prompt

    def retrieve_text(self, query: str, top_k: int = 10):
        """Retrieve text chunks using existing logic"""
        if top_k <= 0:
            return []
        q_vec = self.retriever.encode(query, convert_to_numpy=True,
                                      normalize_embeddings=True).astype("float32")
        scores, indices = self.index.search(q_vec.reshape(1, -1), top_k)
        indices = indices.flatten()
        if len(indices) == 0:
            return []

        return [
            {"text": self.corpus[i],
             "score": float(scores[0][j]),
             "index": int(i),
             "type": "text"}
            for j, i in enumerate(indices)
        ]

    def retrieve_video(self, query: str, top_k: int = 5):
        """Retrieve video segments using query-transcript similarity"""
        if not self.video_data:
            return []

        # Use transcript similarity for video retrieval
        video_texts = [seg.get('transcript', '') for seg in self.video_data]

        # Filter out empty transcripts
        valid_segments = [(i, seg, text) for i, (seg, text) in enumerate(zip(self.video_data, video_texts)) if text.strip()]

        if not valid_segments:
            return []

        valid_indices, valid_segs, valid_texts = zip(*valid_segments)

        # Encode query and video transcripts
        q_vec = self.retriever.encode(query, convert_to_numpy=True, normalize_embeddings=True)
        text_vecs = self.retriever.encode(valid_texts, convert_to_numpy=True, normalize_embeddings=True)

        # Compute similarity scores
        similarities = np.dot(text_vecs, q_vec)

        # Get top-k results
        top_indices = np.argsort(similarities)[::-1][:top_k]

        def clean_transcript(text):
            """Clean transcript text to prevent generation issues"""
            import re
            # Remove non-ASCII characters and normalize whitespace
            text = re.sub(r'[^\x00-\x7F]+', ' ', text)
            text = re.sub(r'\s+', ' ', text)
            text = text.strip()
            # Limit length to prevent overwhelming context
            return text[:500] if len(text) > 500 else text

        return [
            {
                "text": f"Video segment from {valid_segs[idx]['phase']} phase: {clean_transcript(valid_segs[idx]['transcript'])}",
                "score": float(similarities[idx]),
                "index": valid_indices[idx],
                "type": "video",
                "video_segment": valid_segs[idx]
            }
            for idx in top_indices
        ]

    def retrieve(self, query: str, top_k: int = 20, rerank_k: int = 5):
        """MODIFIED: Combined text and video retrieval + optional cross-encoder rerank."""
        # Calculate split for text vs video retrieval
        text_k = int(top_k * (1 - self.video_weight))
        video_k = int(top_k * self.video_weight)

        # Ensure at least 1 of each if available
        text_k = max(1, text_k) if self.corpus else 0
        video_k = max(1, video_k) if self.video_data else 0

        all_results = []

        # Retrieve text chunks
        if text_k > 0:
            text_results = self.retrieve_text(query, text_k)
            all_results.extend(text_results)

        # Retrieve video segments
        if video_k > 0:
            video_results = self.retrieve_video(query, video_k)
            all_results.extend(video_results)

        if not all_results:
            return []

        # No-reranker shortcut
        if self.reranker_model is None or self.reranker_tokenizer is None:
            all_results.sort(key=lambda x: x["score"], reverse=True)
            return all_results[:rerank_k]

        # Cross-encoder reranking
        pairs = [(query, result["text"]) for result in all_results]
        inputs = self.reranker_tokenizer(pairs, padding=True, truncation=True, max_length=512, return_tensors='pt')
        inputs = {k: v.to(self.reranker_model.device) for k, v in inputs.items()}
        with torch.inference_mode():
            logits = self.reranker_model(**inputs).logits.squeeze(-1).cpu().numpy().astype(float)

        ranked = logits.argsort()[::-1][:rerank_k]
        return [all_results[i] for i in ranked]

    def generate_answer(self, query: str, context_items: list, max_new_tokens: int = 256, temperature: float = 0.0):
        """MODIFIED: Generate answer with both text and video context"""
        prompt = self.system_prompt or ""

        # Separate text and video contexts
        text_contexts = [item for item in context_items if item.get("type") == "text"]
        video_contexts = [item for item in context_items if item.get("type") == "video"]

        # Add text context
        if text_contexts:
            prompt += "Text Sources:\n"
            for item in text_contexts:
                ctx_text = item["text"].replace("\n", " ")
                prompt += f"- {ctx_text}\n"

        # Add video context
        if video_contexts:
            prompt += "\nVideo Sources:\n"
            for item in video_contexts:
                prompt += f"- {item['text']}\n"

        prompt += f"\nQuery: {query}\nAnswer:"

        # DEBUG: Check prompt construction
        print(f"System prompt length: {len(self.system_prompt) if self.system_prompt else 0}")
        print(f"Full prompt length: {len(prompt)}")
        print(f"Context items: {len(context_items)} ({len(text_contexts)} text, {len(video_contexts)} video)")
        print(f"Prompt preview: {prompt[:200]}...")

        # Tokenize prompt (truncated if too long for context window)
        inputs = self.generator_tokenizer(prompt, return_tensors='pt', truncation=True,
                                         max_length=self.generator_tokenizer.model_max_length)
        inputs = {k: v.to(self.device) for k,v in inputs.items()}

        print(f"Input token length: {inputs['input_ids'].shape[1]}")

        # Text generation with the LLM
        with torch.inference_mode(), torch.autocast(device_type=self.device, dtype=torch.bfloat16, enabled=(self.device=='cuda')):
          output_ids = self.generator_model.generate(
          **inputs,
          max_new_tokens=128,
          temperature=0.0,
          do_sample=False,
          repetition_penalty=1.0,
          pad_token_id=self.generator_tokenizer.eos_token_id,
          eos_token_id=self.generator_tokenizer.eos_token_id,
          stopping_criteria=None)

        # DEBUG: Check generation output
        print(f"Generated token length: {output_ids.shape[1]}")
        output_text = self.generator_tokenizer.decode(output_ids[0], skip_special_tokens=True)
        print(f"Raw output length: {len(output_text)}")
        print(f"Raw output preview: {output_text[:300]}...")

        # clean prompt:
        answer = output_text[len(prompt):].strip()
        answer = answer.split('\n\nQuery:')[0].strip()  # Stop at next query

        # DEBUG: Check answer extraction
        print(f"Answer after prompt removal: '{answer[:100]}...'")
        print(f"Answer length: {len(answer)}")

        junk_phrases = ["Sure, here is the answer:", "Certainly:", "Certainly. "]
        for jp in junk_phrases:
            answer = answer.replace(jp, "")

        print(f"Final answer: '{answer[:100]}...'")
        return answer

    def __call__(self, query: str, return_context: bool = False):
        """End-to-end answer generation for a given query. If return_context is True, also return the retrieved context passages."""
        context_items = self.retrieve(query)
        if len(context_items) == 0:
            return ("I'm sorry, I could not find relevant information to answer that.", []) if return_context else \
                   "I'm sorry, I could not find relevant information to answer that."
        answer = self.generate_answer(query, context_items)
        return (answer, context_items) if return_context else answer

# Eval/Ablation

In [ ]:
BIOBERT_PATH = "pritamdeka/BioBERT-mnli-snli-scinli-scitail-mednli-stsb"

In [ ]:
# new

SYSTEM_PROMPT_FEWSHOT = """
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious complication of laparoscopic cholecystectomy?
Answer: The most serious complication is bile duct injury (BDI). Although relatively rare (~0.2–0.4% of cases), it can lead to re-operations, higher mortality, reduced quality of life, and litigation.

Example 2:
Query: Why is the critical view of safety important in laparoscopic cholecystectomy?
Answer: The critical view of safety prevents bile duct injury by ensuring anatomy is clearly identified before division. It requires clearing the hepatocystic triangle of fat and tissue, separating the gallbladder from the liver, and confirming that only the cystic duct and cystic artery are seen entering the gallbladder.

Now use the context items below to answer the user query.
Context:
"""

SYSTEM_PROMPT_NO_FEWSHOT = """You are a surgical QA assistant. Use ONLY the provided text and video context to answer.
Be concise, factual, and cite only information present in the context.
Context:
"""

In [ ]:
# index_dummy for testing
import faiss

# existing FAISS index
index_dummy = faiss.read_index("indices/docs.idx")
print(f"Loaded existing index with {index_dummy.ntotal} vectors")

Loaded existing index with 19 vectors

In [ ]:
def test_video_integration():
    """Quick test to verify video data loading"""
    video_path = "/content/drive/MyDrive/SurgiRAG/surgirag_data.json"
    if os.path.exists(video_path):
        with open(video_path, 'r') as f:
            data = json.load(f)
        print(f"Video data found: {len(data)} segments")

        # DEBUG: Check transcript content
        print("\nSample transcripts:")
        for i in range(min(3, len(data))):
            transcript = data[i].get('transcript', '')
            print(f"Transcript {i+1}: '{transcript[:100]}...'")
            print(f"Length: {len(transcript)}")

            # Check for problematic patterns
            if 'when' in transcript.lower() and transcript.lower().count('when') > 5:
                print(f"WARNING: Repetitive 'when' pattern detected")

        # Test a sample query - USE FULL text_chunks to match the index
        test_pipeline = RAGPipeline(
            retriever_model_path=BIOBERT_PATH,
            corpus_chunks=text_chunks,  # Changed from text_chunks[:5] to text_chunks
            faiss_index=index_dummy,
            video_data_path=video_path,
            video_weight=0.5
        )

        results = test_pipeline.retrieve("cystic artery", top_k=5)
        video_count = len([r for r in results if r.get('type') == 'video'])
        text_count = len([r for r in results if r.get('type') == 'text'])

        print(f"Retrieved {text_count} text + {video_count} video segments")

        # Show sample results
        for i, result in enumerate(results[:2]):
            print(f"\nResult {i+1} ({result['type']}):")
            print(f"  Score: {result['score']:.3f}")
            print(f"  Text: {result['text'][:80]}...")

        return True
    else:
        print(f"Video data not found at {video_path}")
        return False

# Run the test
video_working = test_video_integration()

Video data found: 77 segments

Sample transcripts:
Transcript 1: 'This is Dr. Cal Shipley with a review of laparoscopic cholecystectomy. Compared to the single large ...'
Length: 448
Transcript 2: 'The primary disadvantage of the laparoscopic approach for gallbladder removal is in cases where the ...'
Length: 431
Transcript 3: 'The ports act as conduits, allowing various instruments to be inserted through the abdominal wall in...'
Length: 456

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/691 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/433M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/412 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/433M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/443 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/279 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/801 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.24G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/55.8k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/454 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/5.07k [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/89.4k [00:00<?, ?B/s]

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

model-00001-of-00005.safetensors:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

model-00002-of-00005.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

model-00003-of-00005.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

model-00004-of-00005.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00005-of-00005.safetensors:   0%|          | 0.00/1.47G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/215 [00:00<?, ?B/s]

Loaded 77 video segments for transcript-based retrieval

/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `XLMRobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

Retrieved 2 text + 2 video segments

Result 1 (text):
  Score: 0.321
  Text:  dissection; (II) the lower one third of the gallbladder is separated from the l...

Result 2 (video):
  Score: 0.559
  Text: Video segment from dissection phase: So I want to divide that fold to see the in...

In [ ]:
def evaluate_retrieval(
    retriever,
    faiss_index,
    queries: list[str],
    gold_doc_ids: list[set[int]],
    top_k: int = 20,
    batch_size: int = 64,
):
    """Return corpus‑level metrics and per‑query arrays."""

    # Encode all queries in batches
    q_vecs = retriever.encode(
        queries,
        batch_size=batch_size,
        convert_to_numpy=True,
        normalize_embeddings=True,
    ).astype("float32")

    # Single FAISS call for all queries
    scores, all_indices = faiss_index.search(q_vecs, top_k)   # (N, K)

    # Vectorized metrics
    log_discounts = 1.0 / np.log2(np.arange(2, top_k + 2))    # (K,)

    recall_vec      = np.zeros(len(queries))
    rr_vec          = np.zeros(len(queries))
    ndcg_vec        = np.zeros(len(queries))

    for i, retrieved in enumerate(all_indices):
        rel_mask          = np.in1d(retrieved, list(gold_doc_ids[i]), assume_unique=True)
        if rel_mask.any():
            recall_vec[i] = 1.0
            first_rel_idx = np.argmax(rel_mask)
            rr_vec[i]     = 1.0 / (first_rel_idx + 1)

            dcg = (rel_mask * log_discounts).sum()
            ideal_len = min(len(gold_doc_ids[i]), top_k)
            ideal_dcg = log_discounts[:ideal_len].sum()
            ndcg_vec[i] = dcg / ideal_dcg
        else:
            # no relevant docs retrieved
            recall_vec[i] = rr_vec[i] = ndcg_vec[i] = 0.0

    return (
        {"Recall@20": recall_vec.mean(), "MRR": rr_vec.mean(), "nDCG@20": ndcg_vec.mean()},
        {"recall": recall_vec.tolist(), "rr": rr_vec.tolist(), "ndcg": ndcg_vec.tolist()}
    )

In [ ]:
bleu_metric      = evaluate.load("bleu")
rouge_metric     = evaluate.load("rouge")
bertscore_metric = evaluate.load("bertscore")

#on cpu to save vram
device_cpu = "cpu"

factcc_tokenizer = AutoTokenizer.from_pretrained("manueldeprada/FactCC")
factcc_model = AutoModelForSequenceClassification.from_pretrained("manueldeprada/FactCC").to(device_cpu)
factcc_model.eval()

nli_tokenizer    = AutoTokenizer.from_pretrained("facebook/bart-large-mnli")
nli_model    = AutoModelForSequenceClassification.from_pretrained("facebook/bart-large-mnli").to(device_cpu)
nli_model.eval()

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading extra modules:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading builder script: 0.00B [00:00, ?B/s]

tokenizer_config.json:   0%|          | 0.00/174 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/854 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

BartForSequenceClassification(
  (model): BartModel(
    (shared): BartScaledWordEmbedding(50265, 1024, padding_idx=1)
    (encoder): BartEncoder(
      (embed_tokens): BartScaledWordEmbedding(50265, 1024, padding_idx=1)
      (embed_positions): BartLearnedPositionalEmbedding(1026, 1024)
      (layers): ModuleList(
        (0-11): 12 x BartEncoderLayer(
          (self_attn): BartAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (activation_fn): GELUActivation()
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layernorm_embedding): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
    (decoder): BartDecoder(
      (embed_tokens): BartScaledWordEmbedding(50265, 1024, padding_idx=1)
      (embed_positions): BartLearnedPositionalEmbedding(1026, 1024)
      (layers): ModuleList(
        (0-11): 12 x BartDecoderLayer(
          (self_attn): BartAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (activation_fn): GELUActivation()
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (encoder_attn): BartAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (encoder_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layernorm_embedding): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
  )
  (classification_head): BartClassificationHead(
    (dense): Linear(in_features=1024, out_features=1024, bias=True)
    (dropout): Dropout(p=0.0, inplace=False)
    (out_proj): Linear(in_features=1024, out_features=3, bias=True)
  )
)

In [ ]:
@torch.inference_mode()
def _batched_factcc(ctx_batch, ans_batch, tok, model):
    enc = tok(ctx_batch, ans_batch, truncation= True,
              padding=True, max_length=512, return_tensors="pt").to(model.device)
    logits = model(**enc).logits
    probs  = torch.softmax(logits, dim=1)[:, model.config.label2id["CORRECT"]]
    return probs.detach().cpu().numpy()

@torch.inference_mode()
def _batched_nli(ctx_batch, ans_batch, tok, model):
    enc = tok(ctx_batch, ans_batch, truncation=True,
              padding=True, max_length=512, return_tensors="pt").to(model.device)
    logits = model(**enc).logits
    entail = torch.softmax(logits, dim=1)[:, 0]   # entailment index
    return entail.detach().cpu().numpy()

def evaluate_generation(preds, refs, ctxs, batch_size=16):
    if ctxs is None:
        raise ValueError("contexts needed for factuality metrics.")

    # Overlap metrics
    bleu = bleu_metric.compute(
        predictions=preds,
        references=[[r] for r in refs],
        max_order=4,
    )["bleu"]

    rouge = rouge_metric.compute(
        predictions=preds,
        references=refs,
        rouge_types=["rougeL"],
        use_stemmer=True,
    )["rougeL"]

    bert_list = bertscore_metric.compute(
        predictions=preds,
        references=refs,
        lang="en",
        batch_size=batch_size,
    )["f1"]
    bert_arr  = np.asarray(bert_list, dtype=float)
    bert_f1   = float(bert_arr.mean())

    # Factuality (FactCC + NLI) batched
    factcc_probs, entail_probs = [], []
    for start in range(0, len(preds), batch_size):
        slice_preds = preds[start:start + batch_size]
        slice_ctxs  = ctxs[start:start + batch_size]
        factcc_probs.extend(_batched_factcc(slice_ctxs, slice_preds,
                                            factcc_tokenizer, factcc_model))
        entail_probs.extend(_batched_nli(slice_ctxs, slice_preds,
                                         nli_tokenizer, nli_model))

    factcc_probs  = np.array(factcc_probs)
    entail_probs  = np.array(entail_probs)

    return {
        "BLEU":           bleu,
        "ROUGE-L_F1":     rouge,
        "BERTScore_F1":   bert_f1,
        "FactCC_acc":     float((factcc_probs > 0.5).mean()),
        "FactCC_conf":    float(factcc_probs.mean()),
        "Entailment_avg": float(entail_probs.mean()),
        "per_query": {
            "bert_f1":   bert_arr.tolist(),
            "factcc":    factcc_probs.tolist(),
            "entail":    entail_probs.tolist(),
        }
    }

In [ ]:
json_path = "/content/drive/MyDrive/fMRIwork/eval/lc_qa_comprehensive.json"

with open(json_path) as f:
    data = json.load(f)

dataset = Dataset.from_list(data)

In [ ]:
os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')

In [ ]:
index_cache      = {}
retriever_cache  = {}
CROSS_ENCODER    = None
BASE_GENERATOR   = None

In [ ]:
def get_or_build_index_cpu(retr_path: str):
    if retr_path in index_cache:
        return index_cache[retr_path]

    logging.info("FAISS index for %s …", retr_path)
    retr = retriever_cache.get(retr_path)
    if retr is None:
        retr = SentenceTransformer(retr_path, device="cuda")
        retriever_cache[retr_path] = retr

    # processed_pages already has token_chunks
    embs, _, _ = embed_text(processed_pages, retr, batch_size=128)
    idx = build_index(embs, use_gpu=False)
    index_cache[retr_path] = idx
    torch.cuda.empty_cache()
    return idx

In [ ]:
def get_base_generator():
    """Load LLaMA‑3 11B (fp16) once and reuse."""
    global BASE_GENERATOR
    if BASE_GENERATOR is None:
        BASE_GENERATOR = AutoModelForCausalLM.from_pretrained(
            "meta-llama/Llama-3.2-11B-Vision-Instruct",
            device_map="auto",
            torch_dtype=torch.float16,
        )
        BASE_GENERATOR.eval()
    return BASE_GENERATOR

In [ ]:
# Async LLM‑judge ablation loop
# CONFIG
openai.api_key   = os.getenv("OPENAI_API_KEY")
client           = AsyncOpenAI()
GPT_MODEL        = "gpt-4o-mini"
RATE_LIMIT       = AsyncLimiter(max_rate=60, time_period=60)   # 60 req / min
SAMPLE_N         = 5 #turn to 30 later                                        # per combo
random.seed(42)

# async GPT call
async def _chat(prompt: str, max_tokens: int = 1, temperature: float = 0.0,
                retries: int = 3) -> str:
    for attempt in range(retries):
        try:
            async with RATE_LIMIT:
                resp = await asyncio.wait_for(
                    client.chat.completions.create(
                        model=GPT_MODEL,
                        temperature=temperature,
                        max_tokens=max_tokens,
                        messages=[
                            {"role": "system",
                             "content": "You are a strict evaluator. "
                                        "Answer ONLY with the requested output."},
                            {"role": "user", "content": prompt}
                        ],
                    ),
                    timeout=120,
                )
                return resp.choices[0].message.content.strip()
        except (asyncio.TimeoutError, Exception) as e:
            logging.warning("GPT call failed (attempt %d/%d): %s",
                            attempt + 1, retries, str(e))
            await asyncio.sleep(1 + attempt)
    return ""    # fall‑back

# LLM‑Judge metrics
async def context_precision(question: str, chunks: list[str]) -> float:
    bullets = "\n".join([f"- {c[:300]}" for c in chunks[:5]])
    prompt  = (f"Question: {question}\n\n"
               f"Context chunks:\n{bullets}\n\n"
               "Do these chunks collectively help answer the question? "
               "Reply only YES or NO.")
    resp = await _chat(prompt)
    return 1.0 if resp.lower().startswith("y") else 0.0

async def faithfulness_score(answer: str, context: str) -> float:
    prompt = (f"Context:\n\"\"\"{context[:4096]}\"\"\"\n\n"
              f"Answer:\n\"\"\"{answer[:2048]}\"\"\"\n\n"
              "Does the context fully support every factual claim in the answer? "
              "Respond with a single number 0‑1.")
    resp = await _chat(prompt, max_tokens=3)
    try:
        return float(resp.split()[0])
    except ValueError:
        return 0.0

async def fluency_coherence(answer: str) -> dict[str, float]:
    prompt = ("Rate the answer below on a 1‑5 integer scale for each trait.\n\n"
              "Traits: (A) Fluency/Grammar, (B) Coherence/Logical‑flow.\n\n"
              "Return JSON exactly like {\"fluency\":4, \"coherence\":5}.\n\n"
              f"Answer:\n\"\"\"{answer[:4096]}\"\"\"")
    resp = await _chat(prompt, max_tokens=15)
    try:
        return json.loads(resp)
    except Exception:
        return {"fluency": 1, "coherence": 1}



# EXPERIMENT MATRIX

retriever_variants = {
    "random": None,                 # special-cased
    "base":   BIOBERT_PATH,         # BioBERT encoder
    "fine":   retr_model_path       # FT encoder
}

reranker_variants = {
    "none":  None,
    "cross": "BAAI/bge-reranker-large",
}

generator_variants = {
    "base":   {"base_model": base_gen_model, "lora": None,        "fewshot": True},
    "fine":   {"base_model": base_gen_model, "lora": adapter_dir, "fewshot": True},
    # "no_fs":  {"base_model": base_gen_model, "lora": None,        "fewshot": False},
    # "fine_no_fs": {"base_model": base_gen_model, "lora": adapter_dir, "fewshot": False},
}

# Cached heavy models

retriever_cache = {path: SentenceTransformer(path, device="cuda")
                   for path in {v for v in retriever_variants.values() if v}}
cross_encoder = None
base_generator = None  # load once; apply LoRA adapters later when called

results_table = []
tqdm.write("Async GPT‑judge ablations…")

Async GPT‑judge ablations…

In [ ]:
dummy_path = BIOBERT_PATH
index_dummy = get_or_build_index_cpu(dummy_path)

Total chunks: 19
Embeddings tensor shape: torch.Size([19, 768])
Building exact IndexFlatIP …
Index built with 19 vectors  |  dim = 768

In [ ]:
async def run_one_combo(r_name, rerank_name, g_name, sample_pairs):
    """
    Build a pipeline variant, answer SAMPLE_N questions, gather classic +
    GPT‑judge metrics, and append a dict to `results_table`.
    """
    global CROSS_ENCODER

    combo_name = f"{r_name}_retr-{rerank_name}_rerank-{g_name}_gen"
    print(f"Running combo: {combo_name}")

    # Generator setup
    gen_cfg = generator_variants[g_name]
    base_gen = get_base_generator()

    if gen_cfg["lora"] is None:
      generator_to_use = base_gen
    else:
      # apply LoRA, don't merge to avoid corruption
      generator_to_use = PeftModel.from_pretrained(
          base_gen, gen_cfg["lora"], device_map="auto").eval()

    # Retriever + FAISS index
    if r_name == "random":
        index_for_retr = None
    else:
        retr_path = retriever_variants[r_name]
        index_for_retr = get_or_build_index_cpu(retr_path)

    # Build/Reuse reranker
    if reranker_variants[rerank_name] is None:
        reranker_model_name = None
        shared_reranker_obj = None
    else:
        reranker_model_name = reranker_variants[rerank_name]
        if CROSS_ENCODER is None:
            CROSS_ENCODER = AutoModelForSequenceClassification.from_pretrained(
                reranker_model_name, device_map="auto", torch_dtype=torch.float16
            )
        shared_reranker_obj = CROSS_ENCODER

    use_fs = gen_cfg.get("fewshot", True)

    if r_name == "random":
        class RandomRetriever(RAGPipeline):
            def __init__(self, corpus_chunks, generator_object):
                self.corpus = corpus_chunks
                self.device = "cuda" if torch.cuda.is_available() else "cpu"
                self.retriever = None
                self.index = None
                self.reranker_model = None
                self.reranker_tokenizer = None
                self.generator_model = generator_object
                self.generator_tokenizer = AutoTokenizer.from_pretrained(
                    base_gen_model, trust_remote_code=True)
                self.system_prompt = " "

                # Add video attributes for compatibility
                self.video_data = None
                self.video_weight = 0.3

            def retrieve(self, query, top_k=20, rerank_k=5):
                total = len(self.corpus)
                idxs = np.random.choice(total, size=min(top_k, total), replace=False)
                return [{"text": self.corpus[i], "index": int(i), "score": None, "type": "text"}
                        for i in idxs[:rerank_k]]

        pipeline_variant = RandomRetriever(
            corpus_chunks=text_chunks,
            generator_object=generator_to_use
        )
        pipeline_variant.system_prompt = SYSTEM_PROMPT_FEWSHOT if use_fs else SYSTEM_PROMPT_NO_FEWSHOT

    else:
        pipeline_variant = RAGPipeline(
            retriever_model_path=retriever_variants[r_name],
            corpus_chunks=text_chunks,
            faiss_index=index_for_retr,
            reranker_model_name=reranker_model_name,
            generator_object=generator_to_use,
            shared_reranker=shared_reranker_obj,
            shared_retriever=retriever_cache.get(retriever_variants[r_name]),
            system_prompt=SYSTEM_PROMPT_FEWSHOT if use_fs else SYSTEM_PROMPT_NO_FEWSHOT,
            # NEW: Add video integration
            video_data_path="/content/drive/MyDrive/SurgiRAG/surgirag_data.json",
            video_weight=0.3  # 30% video, 70% text
        )

    # Answer SAMPLE_N questions
    preds, ctx_texts, refs, qs = [], [], [], []
    for i, (q, ref) in enumerate(sample_pairs):
        print(f"\nProcessing question {i+1}/{len(sample_pairs)}: {q[:50]}...")

        ctx_items = pipeline_variant.retrieve(q, top_k=20, rerank_k=5)
        print(f"Retrieved {len(ctx_items)} items")

        if ctx_items:
            total_chars = sum(len(item['text']) for item in ctx_items)
            print(f"Total context chars: {total_chars}")
            types = [item.get('type', 'unknown') for item in ctx_items]
            print(f"Types: {types}")
        else:
            print("No items retrieved")

        ans = pipeline_variant.generate_answer(q, ctx_items, temperature=0.2)

        preds.append(ans)
        refs.append(ref)
        qs.append(q)
        ctx_texts.append(" ".join(it["text"] for it in ctx_items))

    # Classic metrics
    classic = evaluate_generation(preds, refs, ctx_texts)

    # GPT‑judge metrics
    coros = [
        asyncio.gather(
            context_precision(q, ctx.split("\n\n")[:5]),
            faithfulness_score(a, ctx),
            fluency_coherence(a)
        )
        for q, a, ctx in zip(qs, preds, ctx_texts)
    ]
    results_triplets = await asyncio.gather(*coros)

    prec_vals = [t[0] for t in results_triplets]
    faith_vals = [t[1] for t in results_triplets]
    flu_vals = [t[2]["fluency"] for t in results_triplets]
    coh_vals = [t[2]["coherence"] for t in results_triplets]

    gpt_metrics = {
        "GPT_Prec@5": float(np.mean(prec_vals)),
        "GPT_Faith": float(np.mean(faith_vals)),
        "GPT_Fluency": float(np.mean(flu_vals)),
        "GPT_Coherence": float(np.mean(coh_vals)),
    }

    # combo_name = f"{r_name}_retr-{rerank_name}_rerank-{g_name}_gen"

    metrics = {**classic, **gpt_metrics, "combo": combo_name}

    # add per-query payloads
    if "per_query" in classic:
        metrics["per_query_json"] = json.dumps(classic["per_query"])
    if "retrieval_per_query" in locals():
        metrics["retrieval_per_query_json"] = json.dumps(retrieval_per_query)

    results_table.append(metrics)
    logging.info("finished %s", combo_name)

    # cleanup aggressive
    del pipeline_variant.generator_model
    del pipeline_variant.retriever
    if hasattr(pipeline_variant, 'reranker_model'):
        del pipeline_variant.reranker_model
    del pipeline_variant, generator_to_use
    torch.cuda.empty_cache()
    gc.collect()

In [ ]:
import gc
torch.cuda.empty_cache()
torch.cuda.synchronize()
gc.collect()

5763

In [ ]:
nest_asyncio.apply()
logging.basicConfig(level=logging.INFO)

SAMPLE_N = 30 # turn to 30 later                      # Q‑A pairs per combo
random.seed(42)

async def main_ablation():
    # subsample of Q‑A pairs
    sample_pairs = random.sample(
        list(zip([ex["question"] for ex in dataset],
                 [ex["answer"]   for ex in dataset])),
        k=min(SAMPLE_N, len(dataset))
    )

    # product of variant keys
    combos = list(itertools.product(
        retriever_variants.keys(),
        reranker_variants .keys(),
        generator_variants.keys())
    )

    for r_name, rerank_name, g_name in tqdm(combos, desc="Combos"):
        await run_one_combo(r_name, rerank_name, g_name, sample_pairs)

    # save & show
    df = pd.DataFrame(results_table)
    df.to_csv("llm_judge_ablation.csv", index=False)
    display(df.sort_values("GPT_Faith", ascending=False))

    return df

df_results = await main_ablation()

print(f"Index size: {index_dummy.ntotal}")
print(f"Corpus size: {len(text_chunks)}")
print(f"Match: {index_dummy.ntotal == len(text_chunks)}")

Combos:   0%|          | 0/12 [00:00<?, ?it/s]

Running combo: random_retr-none_rerank-base_gen

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

Loading checkpoint shards:   0%|          | 0/5 [00:00<?, ?it/s]

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Processing question 1/30: How should the patient be positioned for laparosco...
Retrieved 5 items
Total context chars: 6232
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7379
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1752

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1880
Raw output length: 7947
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The patient is positioned in the supine position with the arms at their sides, and the table is then...'
Answer length: 567
Final answer: 'The patient is positioned in the supine position with the arms at their sides, and the table is then...'

Processing question 2/30: What are the common indications for laparoscopic c...
Retrieved 5 items
Total context chars: 5845
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6987
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1584

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1712
Raw output length: 7572
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The most common indications for laparoscopic cholecystectomy are symptomatic gallstones, acute chole...'
Answer length: 584
Final answer: 'The most common indications for laparoscopic cholecystectomy are symptomatic gallstones, acute chole...'

Processing question 3/30: Tokyo Guidelines 2018: Recommended management for ...
Retrieved 5 items
Total context chars: 5854
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7011
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1525

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1653
Raw output length: 7668
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Grade III acute cholecystitis is characterized by severe inflammation of the gallbladder with perich...'
Answer length: 656
Final answer: 'Grade III acute cholecystitis is characterized by severe inflammation of the gallbladder with perich...'

Processing question 4/30: How many laparoscopic ports are typically used, an...
Retrieved 5 items
Total context chars: 5558
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6719
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1531

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1659
Raw output length: 7173
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The typical number of laparoscopic ports used is 3, with the camera port placed at the umbilicus. Th...'
Answer length: 452
Final answer: 'The typical number of laparoscopic ports used is 3, with the camera port placed at the umbilicus. Th...'

Processing question 5/30: How does surgeon experience influence outcomes in ...
Retrieved 5 items
Total context chars: 6427
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7583
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1717

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1845
Raw output length: 8337
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. Studies have sh...'
Answer length: 753
Final answer: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. Studies have sh...'

Processing question 6/30: What is the standard approach if gallbladder carci...
Retrieved 5 items
Total context chars: 6242
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7402
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1753

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1881
Raw output length: 8044
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The standard approach is to convert to an open cholecystectomy. This is because the risk of spreadin...'
Answer length: 641
Final answer: 'The standard approach is to convert to an open cholecystectomy. This is because the risk of spreadin...'

Processing question 7/30: What are relative contraindications to laparoscopi...
Retrieved 5 items
Total context chars: 5653
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6798
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1487

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1615
Raw output length: 7469
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The relative contraindications to laparoscopic cholecystectomy include severe obesity, previous uppe...'
Answer length: 670
Final answer: 'The relative contraindications to laparoscopic cholecystectomy include severe obesity, previous uppe...'

Processing question 8/30: Can laparoscopic cholecystectomy be performed for ...
Retrieved 5 items
Total context chars: 5402
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6554
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1569

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1697
Raw output length: 7131
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy can be performed for acalculous cholecystitis, but it is not the first ...'
Answer length: 576
Final answer: 'Laparoscopic cholecystectomy can be performed for acalculous cholecystitis, but it is not the first ...'

Processing question 9/30: What are the absolute contraindications to laparos...
Retrieved 5 items
Total context chars: 5826
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6975
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1581

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1709
Raw output length: 7651
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'There are no absolute contraindications to laparoscopic cholecystectomy. However, certain conditions...'
Answer length: 675
Final answer: 'There are no absolute contraindications to laparoscopic cholecystectomy. However, certain conditions...'

Processing question 10/30: Tokyo Guidelines 2018: How should Grade I acute ch...
Retrieved 5 items
Total context chars: 6616
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7766
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1718

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1846
Raw output length: 8438
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Grade I acute cholecystitis is managed with conservative treatment, which includes fasting, hydratio...'
Answer length: 671
Final answer: 'Grade I acute cholecystitis is managed with conservative treatment, which includes fasting, hydratio...'

Processing question 11/30: How are high‑grade bile leaks managed after cholec...
Retrieved 5 items
Total context chars: 6754
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7891
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1725

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1853
Raw output length: 8488
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'High-grade bile leaks are managed with endoscopic retrograde cholangiopancreatography (ERCP) with st...'
Answer length: 596
Final answer: 'High-grade bile leaks are managed with endoscopic retrograde cholangiopancreatography (ERCP) with st...'

Processing question 12/30: Is cholecystectomy indicated after gallstone pancr...
Retrieved 5 items
Total context chars: 5747
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6882
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1615

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1743
Raw output length: 7508
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The answer is yes. Gallstone pancreatitis is a clear indication for cholecystectomy. Studies have sh...'
Answer length: 624
Final answer: 'The answer is yes. Gallstone pancreatitis is a clear indication for cholecystectomy. Studies have sh...'

Processing question 13/30: What advantages does laparoscopic cholecystectomy ...
Retrieved 5 items
Total context chars: 5224
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6375
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1443

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1571
Raw output length: 7038
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy offers several advantages over open surgery, including reduced postoper...'
Answer length: 663
Final answer: 'Laparoscopic cholecystectomy offers several advantages over open surgery, including reduced postoper...'

Processing question 14/30: When should conversion to open cholecystectomy be ...
Retrieved 5 items
Total context chars: 5286
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6424
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1565

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1693
Raw output length: 7094
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Conversion to open cholecystectomy should be considered when the surgeon is unable to safely complet...'
Answer length: 669
Final answer: 'Conversion to open cholecystectomy should be considered when the surgeon is unable to safely complet...'

Processing question 15/30: Are asymptomatic gallstones an indication for chol...
Retrieved 5 items
Total context chars: 6507
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7646
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1725

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1853
Raw output length: 8321
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, asymptomatic gallstones are not an indication for cholecystectomy. The American Gastroenterologi...'
Answer length: 674
Final answer: 'No, asymptomatic gallstones are not an indication for cholecystectomy. The American Gastroenterologi...'

Processing question 16/30: How should common bile duct stones detected preope...
Retrieved 5 items
Total context chars: 5728
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6875
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1526

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1654
Raw output length: 7484
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Preoperative ERCP with sphincterotomy and stone extraction is recommended for patients with common b...'
Answer length: 608
Final answer: 'Preoperative ERCP with sphincterotomy and stone extraction is recommended for patients with common b...'

Processing question 17/30: When can patients usually resume normal activities...
Retrieved 5 items
Total context chars: 5451
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6614
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1568

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1696
Raw output length: 7287
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. T...'
Answer length: 672
Final answer: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. T...'

Processing question 18/30: What do SAGES guidelines say about routinely achie...
Retrieved 5 items
Total context chars: 6462
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7622
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1739

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1867
Raw output length: 8295
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The SAGES guidelines recommend that the critical view of safety be achieved routinely. This involves...'
Answer length: 672
Final answer: 'The SAGES guidelines recommend that the critical view of safety be achieved routinely. This involves...'

Processing question 19/30: What are the most common intraoperative complicati...
Retrieved 5 items
Total context chars: 5726
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6889
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1513

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1641
Raw output length: 7571
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The most common intraoperative complications of laparoscopic cholecystectomy include bleeding, bile ...'
Answer length: 681
Final answer: 'The most common intraoperative complications of laparoscopic cholecystectomy include bleeding, bile ...'

Processing question 20/30: Is laparoscopic cholecystectomy safe during pregna...
Retrieved 5 items
Total context chars: 6444
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7575
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1686

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1814
Raw output length: 8268
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is generally safe during pregnancy, but it should be performed by exper...'
Answer length: 692
Final answer: 'Laparoscopic cholecystectomy is generally safe during pregnancy, but it should be performed by exper...'

Processing question 21/30: What constitutes the critical view of safety in la...
Retrieved 5 items
Total context chars: 6445
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7599
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1724

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1852
Raw output length: 8223
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The critical view of safety is achieved by clearing the hepatocystic triangle of fat and tissue, sep...'
Answer length: 623
Final answer: 'The critical view of safety is achieved by clearing the hepatocystic triangle of fat and tissue, sep...'

Processing question 22/30: How are postoperative bile leaks diagnosed?...
Retrieved 5 items
Total context chars: 4783
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 5903
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1418

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1546
Raw output length: 6485
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Postoperative bile leaks are diagnosed by imaging studies, such as CT scans or ultrasound, which can...'
Answer length: 581
Final answer: 'Postoperative bile leaks are diagnosed by imaging studies, such as CT scans or ultrasound, which can...'

Processing question 23/30: When should intraoperative cholangiography be perf...
Retrieved 5 items
Total context chars: 6728
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7861
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1744

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1872
Raw output length: 8427
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Intraoperative cholangiography should be performed after the cystic duct is clipped and divided, and...'
Answer length: 565
Final answer: 'Intraoperative cholangiography should be performed after the cystic duct is clipped and divided, and...'

Processing question 24/30: How long is the typical hospital stay after uncomp...
Retrieved 5 items
Total context chars: 5236
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6400
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1516

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1644
Raw output length: 7051
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is reduced.  The exact du...'
Answer length: 650
Final answer: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is reduced.  The exact du...'

Processing question 25/30: Are prophylactic antibiotics required for all lapa...
Retrieved 5 items
Total context chars: 4673
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 5827
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1431

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1559
Raw output length: 6475
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The SAGES Safe...'
Answer length: 646
Final answer: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The SAGES Safe...'

Processing question 26/30: Tokyo Guidelines 2018: Management strategy for Gra...
Retrieved 5 items
Total context chars: 6436
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7589
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1735

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1863
Raw output length: 8218
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend a conservative management strategy for Grade II acute cholecysti...'
Answer length: 628
Final answer: 'The Tokyo Guidelines 2018 recommend a conservative management strategy for Grade II acute cholecysti...'

Processing question 27/30: What is fluorescent indocyanine‑green cholangiogra...
Retrieved 5 items
Total context chars: 6456
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7607
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1728

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1856
Raw output length: 8199
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Fluorescent indocyanine-green cholangiography is a technique used to visualize the biliary tree duri...'
Answer length: 591
Final answer: 'Fluorescent indocyanine-green cholangiography is a technique used to visualize the biliary tree duri...'

Processing question 28/30: What is SAGES guidance on intraoperative cholangio...
Retrieved 5 items
Total context chars: 6376
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7516
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1734

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1862
Raw output length: 8126
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'SAGES recommends performing IOC routinely, but it can be performed selectively based on compelling i...'
Answer length: 609
Final answer: 'SAGES recommends performing IOC routinely, but it can be performed selectively based on compelling i...'

Processing question 29/30: What is the incidence of bile duct injury in lapar...
Retrieved 5 items
Total context chars: 6460
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7611
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1730

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1858
Raw output length: 8229
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Complications are still prevalent and occur in 6–8% of patients. Despite its relative infrequency, t...'
Answer length: 617
Final answer: 'Complications are still prevalent and occur in 6–8% of patients. Despite its relative infrequency, t...'

Processing question 30/30: How are the cystic duct and artery managed once th...
Retrieved 5 items
Total context chars: 5741
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6896
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1682
Generated token length: 1810
Raw output length: 7533
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Once the critical view is achieved, the cystic duct and artery are ligated and divided. The cystic d...'
Answer length: 637
Final answer: 'Once the critical view is achieved, the cystic duct and artery are ligated and divided. The cystic d...'

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1750: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `RobertaSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.58.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.

Running combo: random_retr-none_rerank-fine_gen

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Processing question 1/30: How should the patient be positioned for laparosco...
Retrieved 5 items
Total context chars: 5555
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6702
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1524

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1652
Raw output length: 7365
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'
Answer length: 662
Final answer: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'

Processing question 2/30: What are the common indications for laparoscopic c...
Retrieved 5 items
Total context chars: 6443
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7585
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1750

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1878
Raw output length: 8184
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The common indications for laparoscopic cholecystectomy include symptomatic gallstones, gallbladder ...'
Answer length: 598
Final answer: 'The common indications for laparoscopic cholecystectomy include symptomatic gallstones, gallbladder ...'

Processing question 3/30: Tokyo Guidelines 2018: Recommended management for ...
Retrieved 5 items
Total context chars: 5252
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6409
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1391

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1519
Raw output length: 7124
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should be treat...'
Answer length: 715
Final answer: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should be treat...'

Processing question 4/30: How many laparoscopic ports are typically used, an...
Retrieved 5 items
Total context chars: 5943
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7104
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1624

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1752
Raw output length: 7658
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The typical number of ports used in laparoscopic cholecystectomy is 3-4. The camera port is usually ...'
Answer length: 554
Final answer: 'The typical number of ports used in laparoscopic cholecystectomy is 3-4. The camera port is usually ...'

Processing question 5/30: How does surgeon experience influence outcomes in ...
Retrieved 5 items
Total context chars: 5811
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6967
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1590

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1718
Raw output length: 7663
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. More experience...'
Answer length: 695
Final answer: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. More experience...'

Processing question 6/30: What is the standard approach if gallbladder carci...
Retrieved 5 items
Total context chars: 6387
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7547
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1702

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1830
Raw output length: 8224
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'If gallbladdder carcinoma is suspected during surgery, the surgeon should stop the procedure and con...'
Answer length: 676
Final answer: 'If gallbladdder carcinoma is suspected during surgery, the surgeon should stop the procedure and con...'

Processing question 7/30: What are relative contraindications to laparoscopi...
Retrieved 5 items
Total context chars: 5458
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6603
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1544

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1672
Raw output length: 7223
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Relative contraindications to laparoscopic cholecystectomy include prior upper abdominal surgery, se...'
Answer length: 619
Final answer: 'Relative contraindications to laparoscopic cholecystectomy include prior upper abdominal surgery, se...'

Processing question 8/30: Can laparoscopic cholecystectomy be performed for ...
Retrieved 5 items
Total context chars: 5903
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7055
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1526

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1654
Raw output length: 7595
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is the treatment of choice for acalculous cholecystitis. It is safe and...'
Answer length: 539
Final answer: 'Laparoscopic cholecystectomy is the treatment of choice for acalculous cholecystitis. It is safe and...'

Processing question 9/30: What are the absolute contraindications to laparos...
Retrieved 5 items
Total context chars: 5437
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6586
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1546

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1674
Raw output length: 7256
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'There are no absolute contraindications to laparoscopic cholecystectomy. However, certain conditions...'
Answer length: 669
Final answer: 'There are no absolute contraindications to laparoscopic cholecystectomy. However, certain conditions...'

Processing question 10/30: Tokyo Guidelines 2018: How should Grade I acute ch...
Retrieved 5 items
Total context chars: 6713
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7863
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1715

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1843
Raw output length: 8557
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Grade I acute cholecystitis is characterized by mild symptoms and no signs of inflammation. It can b...'
Answer length: 693
Final answer: 'Grade I acute cholecystitis is characterized by mild symptoms and no signs of inflammation. It can b...'

Processing question 11/30: How are high‑grade bile leaks managed after cholec...
Retrieved 5 items
Total context chars: 6302
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7439
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1730

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1858
Raw output length: 7976
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'High-grade bile leaks are managed with endoscopic retrograde cholangiography and stenting (ERCS) or ...'
Answer length: 536
Final answer: 'High-grade bile leaks are managed with endoscopic retrograde cholangiography and stenting (ERCS) or ...'

Processing question 12/30: Is cholecystectomy indicated after gallstone pancr...
Retrieved 5 items
Total context chars: 6559
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7694
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1688

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1816
Raw output length: 8298
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Cholecystectomy is indicated after gallstone pancreatitis. The critical view of safety prevents bile...'
Answer length: 603
Final answer: 'Cholecystectomy is indicated after gallstone pancreatitis. The critical view of safety prevents bile...'

Processing question 13/30: What advantages does laparoscopic cholecystectomy ...
Retrieved 5 items
Total context chars: 6400
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7551
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1707

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1835
Raw output length: 8203
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy offers several advantages over open surgery, including reduced postoper...'
Answer length: 651
Final answer: 'Laparoscopic cholecystectomy offers several advantages over open surgery, including reduced postoper...'

Processing question 14/30: When should conversion to open cholecystectomy be ...
Retrieved 5 items
Total context chars: 6138
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7276
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1630

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1758
Raw output length: 7947
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Conversion to open cholecystectomy should be considered when the critical view of safety cannot be a...'
Answer length: 671
Final answer: 'Conversion to open cholecystectomy should be considered when the critical view of safety cannot be a...'

Processing question 15/30: Are asymptomatic gallstones an indication for chol...
Retrieved 5 items
Total context chars: 5512
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6651
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1594

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1722
Raw output length: 7323
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, asymptomatic gallstones are not an indication for cholecystectomy. The American Gastroenterologi...'
Answer length: 671
Final answer: 'No, asymptomatic gallstones are not an indication for cholecystectomy. The American Gastroenterologi...'

Processing question 16/30: How should common bile duct stones detected preope...
Retrieved 5 items
Total context chars: 6594
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7741
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1719

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1847
Raw output length: 8434
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Common bile duct stones detected preoperatively should be managed by preoperative ERCP. Preoperative...'
Answer length: 692
Final answer: 'Common bile duct stones detected preoperatively should be managed by preoperative ERCP. Preoperative...'

Processing question 17/30: When can patients usually resume normal activities...
Retrieved 5 items
Total context chars: 5605
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6768
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1624

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1752
Raw output length: 7352
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'
Answer length: 583
Final answer: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'

Processing question 18/30: What do SAGES guidelines say about routinely achie...
Retrieved 5 items
Total context chars: 6414
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7574
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1647

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1775
Raw output length: 8180
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'SAGES guidelines recommend that surgeons should strive to achieve the critical view of safety in all...'
Answer length: 606
Final answer: 'SAGES guidelines recommend that surgeons should strive to achieve the critical view of safety in all...'

Processing question 19/30: What are the most common intraoperative complicati...
Retrieved 5 items
Total context chars: 6380
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7543
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1721

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1849
Raw output length: 8139
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The most common intraoperative complications of laparoscopic cholecystectomy are bile duct injury, b...'
Answer length: 595
Final answer: 'The most common intraoperative complications of laparoscopic cholecystectomy are bile duct injury, b...'

Processing question 20/30: Is laparoscopic cholecystectomy safe during pregna...
Retrieved 5 items
Total context chars: 6415
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7546
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1752

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1880
Raw output length: 8208
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is safe during pregnancy. The procedure is performed under general anes...'
Answer length: 661
Final answer: 'Laparoscopic cholecystectomy is safe during pregnancy. The procedure is performed under general anes...'

Processing question 21/30: What constitutes the critical view of safety in la...
Retrieved 5 items
Total context chars: 4573
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 5727
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1416

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1544
Raw output length: 6386
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The critical view of safety requires clearing the hepatocystic triangle of fat and tissue, separatin...'
Answer length: 658
Final answer: 'The critical view of safety requires clearing the hepatocystic triangle of fat and tissue, separatin...'

Processing question 22/30: How are postoperative bile leaks diagnosed?...
Retrieved 5 items
Total context chars: 6351
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7471
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1671

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1799
Raw output length: 8151
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Postoperative bile leaks are diagnosed by a combination of clinical presentation, imaging studies, a...'
Answer length: 679
Final answer: 'Postoperative bile leaks are diagnosed by a combination of clinical presentation, imaging studies, a...'

Processing question 23/30: When should intraoperative cholangiography be perf...
Retrieved 5 items
Total context chars: 5913
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7046
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1534

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1662
Raw output length: 7639
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Intraoperative cholangiography should be performed when there is a dilated common bile duct, uncerta...'
Answer length: 592
Final answer: 'Intraoperative cholangiography should be performed when there is a dilated common bile duct, uncerta...'

Processing question 24/30: How long is the typical hospital stay after uncomp...
Retrieved 5 items
Total context chars: 6485
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7649
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1738

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1866
Raw output length: 8261
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'
Answer length: 611
Final answer: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'

Processing question 25/30: Are prophylactic antibiotics required for all lapa...
Retrieved 5 items
Total context chars: 5438
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6592
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1610

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1738
Raw output length: 7227
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The SAGES Safe...'
Answer length: 634
Final answer: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The SAGES Safe...'

Processing question 26/30: Tokyo Guidelines 2018: Management strategy for Gra...
Retrieved 5 items
Total context chars: 6217
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7370
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1642

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1770
Raw output length: 8086
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend a conservative treatment strategy for patients with Grade II acu...'
Answer length: 716
Final answer: 'The Tokyo Guidelines 2018 recommend a conservative treatment strategy for patients with Grade II acu...'

Processing question 27/30: What is fluorescent indocyanine‑green cholangiogra...
Retrieved 5 items
Total context chars: 5485
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6636
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1553

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1681
Raw output length: 7169
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Fluorescent indocyanine‑green cholangiography (ICG-FC) is a novel, real-time, intraoperative imaging...'
Answer length: 533
Final answer: 'Fluorescent indocyanine‑green cholangiography (ICG-FC) is a novel, real-time, intraoperative imaging...'

Processing question 28/30: What is SAGES guidance on intraoperative cholangio...
Retrieved 5 items
Total context chars: 5506
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6646
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1554

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1682
Raw output length: 7252
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Society of Gastrointestinal and Endoscopic Surgeons (SAGES) recommends routine IOC in all patien...'
Answer length: 605
Final answer: 'The Society of Gastrointestinal and Endoscopic Surgeons (SAGES) recommends routine IOC in all patien...'

Processing question 29/30: What is the incidence of bile duct injury in lapar...
Retrieved 5 items
Total context chars: 5637
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6788
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1662

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1790
Raw output length: 7224
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The incidence of bile duct injury in laparoscopic cholecystectomy is 0.2-0.4%. The incidence of bile...'
Answer length: 435
Final answer: 'The incidence of bile duct injury in laparoscopic cholecystectomy is 0.2-0.4%. The incidence of bile...'

Processing question 30/30: How are the cystic duct and artery managed once th...
Retrieved 5 items
Total context chars: 5181
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6336
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1383
Generated token length: 1511
Raw output length: 6953
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The cystic duct and artery are clipped and divided. The cystic duct is clipped at the cystic duct-co...'
Answer length: 617
Final answer: 'The cystic duct and artery are clipped and divided. The cystic duct is clipped at the cystic duct-co...'
Running combo: random_retr-cross_rerank-base_gen

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Processing question 1/30: How should the patient be positioned for laparosco...
Retrieved 5 items
Total context chars: 6482
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7629
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1640

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1768
Raw output length: 8287
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'
Answer length: 658
Final answer: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'

Processing question 2/30: What are the common indications for laparoscopic c...
Retrieved 5 items
Total context chars: 4734
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 5876
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1366

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1494
Raw output length: 6482
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The common indications for laparoscopic cholecystectomy include symptomatic gallstones, gallbladder ...'
Answer length: 605
Final answer: 'The common indications for laparoscopic cholecystectomy include symptomatic gallstones, gallbladder ...'

Processing question 3/30: Tokyo Guidelines 2018: Recommended management for ...
Retrieved 5 items
Total context chars: 5622
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6779
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1646

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1774
Raw output length: 7506
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should undergo ...'
Answer length: 726
Final answer: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should undergo ...'

Processing question 4/30: How many laparoscopic ports are typically used, an...
Retrieved 5 items
Total context chars: 5565
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6726
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1539

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1667
Raw output length: 7189
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Typically, 4 ports are used. The camera port is placed at the umbilicus. The 10 mm port is placed at...'
Answer length: 462
Final answer: 'Typically, 4 ports are used. The camera port is placed at the umbilicus. The 10 mm port is placed at...'

Processing question 5/30: How does surgeon experience influence outcomes in ...
Retrieved 5 items
Total context chars: 6242
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7398
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1657

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1785
Raw output length: 8142
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Surgeon experience is a significant predictor of major complications after laparoscopic cholecystect...'
Answer length: 744
Final answer: 'Surgeon experience is a significant predictor of major complications after laparoscopic cholecystect...'

Processing question 6/30: What is the standard approach if gallbladder carci...
Retrieved 5 items
Total context chars: 5862
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7022
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1594

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1722
Raw output length: 7690
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'If gallbladder carcinoma is suspected during surgery, the standard approach is to convert to an open...'
Answer length: 667
Final answer: 'If gallbladder carcinoma is suspected during surgery, the standard approach is to convert to an open...'

Processing question 7/30: What are relative contraindications to laparoscopi...
Retrieved 5 items
Total context chars: 6516
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7661
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1640

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1768
Raw output length: 8281
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Relative contraindications to laparoscopic cholecystectomy include previous upper abdominal surgery,...'
Answer length: 620
Final answer: 'Relative contraindications to laparoscopic cholecystectomy include previous upper abdominal surgery,...'

Processing question 8/30: Can laparoscopic cholecystectomy be performed for ...
Retrieved 5 items
Total context chars: 5903
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7055
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1617

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1745
Raw output length: 7595
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is the treatment of choice for acalculous cholecystitis. It is safe and...'
Answer length: 539
Final answer: 'Laparoscopic cholecystectomy is the treatment of choice for acalculous cholecystitis. It is safe and...'

Processing question 9/30: What are the absolute contraindications to laparos...
Retrieved 5 items
Total context chars: 5943
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7092
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1619

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1747
Raw output length: 7651
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The absolute contraindications to laparoscopic cholecystectomy are active gallbladder inflammation (...'
Answer length: 558
Final answer: 'The absolute contraindications to laparoscopic cholecystectomy are active gallbladder inflammation (...'

Processing question 10/30: Tokyo Guidelines 2018: How should Grade I acute ch...
Retrieved 5 items
Total context chars: 5106
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6256
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1574

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1702
Raw output length: 6862
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Grade I acute cholecystitis should be managed with antibiotics and supportive care. The patient shou...'
Answer length: 605
Final answer: 'Grade I acute cholecystitis should be managed with antibiotics and supportive care. The patient shou...'

Processing question 11/30: How are high‑grade bile leaks managed after cholec...
Retrieved 5 items
Total context chars: 5581
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6718
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1626

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1754
Raw output length: 7253
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'High-grade bile leaks are managed with endoscopic retrograde cholangiography and stenting (ERCP) and...'
Answer length: 534
Final answer: 'High-grade bile leaks are managed with endoscopic retrograde cholangiography and stenting (ERCP) and...'

Processing question 12/30: Is cholecystectomy indicated after gallstone pancr...
Retrieved 5 items
Total context chars: 5256
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6391
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1518

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1646
Raw output length: 7051
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Yes, cholecystectomy is indicated after gallstone pancreatitis. The critical view of safety prevents...'
Answer length: 660
Final answer: 'Yes, cholecystectomy is indicated after gallstone pancreatitis. The critical view of safety prevents...'

Processing question 13/30: What advantages does laparoscopic cholecystectomy ...
Retrieved 5 items
Total context chars: 6901
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 8052
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1725

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1853
Raw output length: 8704
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy offers several advantages over open surgery, including reduced postoper...'
Answer length: 651
Final answer: 'Laparoscopic cholecystectomy offers several advantages over open surgery, including reduced postoper...'

Processing question 14/30: When should conversion to open cholecystectomy be ...
Retrieved 5 items
Total context chars: 5654
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6792
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1575

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1703
Raw output length: 7494
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Conversion to open cholecystectomy should be considered when the surgeon feels that the operation ca...'
Answer length: 701
Final answer: 'Conversion to open cholecystectomy should be considered when the surgeon feels that the operation ca...'

Processing question 15/30: Are asymptomatic gallstones an indication for chol...
Retrieved 5 items
Total context chars: 5232
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6371
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1462

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1590
Raw output length: 7014
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, asymptomatic gallstones are not an indication for cholecystectomy. The American Gastroenterologi...'
Answer length: 643
Final answer: 'No, asymptomatic gallstones are not an indication for cholecystectomy. The American Gastroenterologi...'

Processing question 16/30: How should common bile duct stones detected preope...
Retrieved 5 items
Total context chars: 6628
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7775
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1704

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1832
Raw output length: 8460
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Common bile duct stones detected preoperatively should be managed with preoperative ERCP. Common bil...'
Answer length: 684
Final answer: 'Common bile duct stones detected preoperatively should be managed with preoperative ERCP. Common bil...'

Processing question 17/30: When can patients usually resume normal activities...
Retrieved 5 items
Total context chars: 5691
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6854
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1519

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1647
Raw output length: 7449
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'
Answer length: 594
Final answer: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'

Processing question 18/30: What do SAGES guidelines say about routinely achie...
Retrieved 5 items
Total context chars: 5815
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6975
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1596

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1724
Raw output length: 7632
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The SAGES Safe Cholecystectomy Program recommends routinely achieving the critical view of safety to...'
Answer length: 656
Final answer: 'The SAGES Safe Cholecystectomy Program recommends routinely achieving the critical view of safety to...'

Processing question 19/30: What are the most common intraoperative complicati...
Retrieved 5 items
Total context chars: 5762
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6925
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1526

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1654
Raw output length: 7551
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The most common intraoperative complications of laparoscopic cholecystectomy are bile duct injury, b...'
Answer length: 625
Final answer: 'The most common intraoperative complications of laparoscopic cholecystectomy are bile duct injury, b...'

Processing question 20/30: Is laparoscopic cholecystectomy safe during pregna...
Retrieved 5 items
Total context chars: 6497
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7628
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1684

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1812
Raw output length: 8275
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is safe during pregnancy. The procedure is performed under general anes...'
Answer length: 646
Final answer: 'Laparoscopic cholecystectomy is safe during pregnancy. The procedure is performed under general anes...'

Processing question 21/30: What constitutes the critical view of safety in la...
Retrieved 5 items
Total context chars: 4469
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 5623
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1343

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1471
Raw output length: 6276
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The critical view of safety requires clearing the hepatocystic triangle of fat and tissue, separatin...'
Answer length: 653
Final answer: 'The critical view of safety requires clearing the hepatocystic triangle of fat and tissue, separatin...'

Processing question 22/30: How are postoperative bile leaks diagnosed?...
Retrieved 5 items
Total context chars: 5650
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6770
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1531

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1659
Raw output length: 7415
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Postoperative bile leaks are diagnosed by a combination of clinical presentation, laboratory tests, ...'
Answer length: 644
Final answer: 'Postoperative bile leaks are diagnosed by a combination of clinical presentation, laboratory tests, ...'

Processing question 23/30: When should intraoperative cholangiography be perf...
Retrieved 5 items
Total context chars: 5918
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7051
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1601

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1729
Raw output length: 7640
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Intraoperative cholangiography should be performed when there is suspicion of CBD stones (history of...'
Answer length: 588
Final answer: 'Intraoperative cholangiography should be performed when there is suspicion of CBD stones (history of...'

Processing question 24/30: How long is the typical hospital stay after uncomp...
Retrieved 5 items
Total context chars: 6358
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7522
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1731

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1859
Raw output length: 8142
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'
Answer length: 619
Final answer: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'

Processing question 25/30: Are prophylactic antibiotics required for all lapa...
Retrieved 5 items
Total context chars: 5589
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6743
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1557

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1685
Raw output length: 7353
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The SAGES Safe...'
Answer length: 609
Final answer: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The SAGES Safe...'

Processing question 26/30: Tokyo Guidelines 2018: Management strategy for Gra...
Retrieved 5 items
Total context chars: 6043
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7196
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1741

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1869
Raw output length: 7715
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend a step-up approach for the management of acute cholecystitis. Th...'
Answer length: 518
Final answer: 'The Tokyo Guidelines 2018 recommend a step-up approach for the management of acute cholecystitis. Th...'

Processing question 27/30: What is fluorescent indocyanine‑green cholangiogra...
Retrieved 5 items
Total context chars: 5337
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6488
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1565

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1693
Raw output length: 7061
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'luorescent indocyanine‑green cholangiography (ICG-FC) is a novel, real-time, intraoperative imaging ...'
Answer length: 573
Final answer: 'luorescent indocyanine‑green cholangiography (ICG-FC) is a novel, real-time, intraoperative imaging ...'

Processing question 28/30: What is SAGES guidance on intraoperative cholangio...
Retrieved 5 items
Total context chars: 5911
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7051
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1672

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1800
Raw output length: 7659
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'AGES guidance on IOC is that it is not required for all patients undergoing laparoscopic cholecystec...'
Answer length: 608
Final answer: 'AGES guidance on IOC is that it is not required for all patients undergoing laparoscopic cholecystec...'

Processing question 29/30: What is the incidence of bile duct injury in lapar...
Retrieved 5 items
Total context chars: 5547
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6698
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1574

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1702
Raw output length: 7191
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Although relatively rare (~0.2–0.4% of cases), bile duct injury (BDI) can lead to re-operations, hig...'
Answer length: 492
Final answer: 'Although relatively rare (~0.2–0.4% of cases), bile duct injury (BDI) can lead to re-operations, hig...'

Processing question 30/30: How are the cystic duct and artery managed once th...
Retrieved 5 items
Total context chars: 6469
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7624
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1716
Generated token length: 1844
Raw output length: 8220
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Once the critical view of safety is achieved, the cystic duct and cystic artery are clipped and divi...'
Answer length: 595
Final answer: 'Once the critical view of safety is achieved, the cystic duct and cystic artery are clipped and divi...'
Running combo: random_retr-cross_rerank-fine_gen

/usr/local/lib/python3.11/dist-packages/peft/tuners/tuners_utils.py:190: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(
The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Processing question 1/30: How should the patient be positioned for laparosco...
Retrieved 5 items
Total context chars: 5317
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6464
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1544

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1672
Raw output length: 7061
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'
Answer length: 597
Final answer: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'

Processing question 2/30: What are the common indications for laparoscopic c...
Retrieved 5 items
Total context chars: 6594
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7736
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1720

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1848
Raw output length: 8333
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The common indications for laparoscopic cholecystectomy include symptomatic gallstones, gallbladder ...'
Answer length: 596
Final answer: 'The common indications for laparoscopic cholecystectomy include symptomatic gallstones, gallbladder ...'

Processing question 3/30: Tokyo Guidelines 2018: Recommended management for ...
Retrieved 5 items
Total context chars: 6389
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7546
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1740

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1868
Raw output length: 8262
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should undergo ...'
Answer length: 715
Final answer: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should undergo ...'

Processing question 4/30: How many laparoscopic ports are typically used, an...
Retrieved 5 items
Total context chars: 6022
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7183
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1712

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1840
Raw output length: 7755
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Typically, 3-4 ports are used. The camera port is placed in the umbilicus. The other ports are place...'
Answer length: 571
Final answer: 'Typically, 3-4 ports are used. The camera port is placed in the umbilicus. The other ports are place...'

Processing question 5/30: How does surgeon experience influence outcomes in ...
Retrieved 5 items
Total context chars: 6560
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7716
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1714

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1842
Raw output length: 8378
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. Studies have sh...'
Answer length: 661
Final answer: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. Studies have sh...'

Processing question 6/30: What is the standard approach if gallbladder carci...
Retrieved 5 items
Total context chars: 5451
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6611
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1530

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1658
Raw output length: 7244
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'If gallbladdar carcinoma is suspected during surgery, the standard approach is to convert to an open...'
Answer length: 633
Final answer: 'If gallbladdar carcinoma is suspected during surgery, the standard approach is to convert to an open...'

Processing question 7/30: What are relative contraindications to laparoscopi...
Retrieved 5 items
Total context chars: 5743
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6888
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1537

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1665
Raw output length: 7458
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Relative contraindications to laparoscopic cholecystectomy include acute cholecystitis, severe obesi...'
Answer length: 569
Final answer: 'Relative contraindications to laparoscopic cholecystectomy include acute cholecystitis, severe obesi...'

Processing question 8/30: Can laparoscopic cholecystectomy be performed for ...
Retrieved 5 items
Total context chars: 6455
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7607
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1627

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1755
Raw output length: 8155
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is the treatment of choice for acalculous cholecystitis. It is safe and...'
Answer length: 548
Final answer: 'Laparoscopic cholecystectomy is the treatment of choice for acalculous cholecystitis. It is safe and...'

Processing question 9/30: What are the absolute contraindications to laparos...
Retrieved 5 items
Total context chars: 5355
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6504
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1506

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1634
Raw output length: 7171
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'There are no absolute contraindications to laparoscopic cholecystectomy. However, certain conditions...'
Answer length: 666
Final answer: 'There are no absolute contraindications to laparoscopic cholecystectomy. However, certain conditions...'

Processing question 10/30: Tokyo Guidelines 2018: How should Grade I acute ch...
Retrieved 5 items
Total context chars: 5023
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6173
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1448

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1576
Raw output length: 6765
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend that Grade I acute cholecystitis should be managed with cholecys...'
Answer length: 591
Final answer: 'The Tokyo Guidelines 2018 recommend that Grade I acute cholecystitis should be managed with cholecys...'

Processing question 11/30: How are high‑grade bile leaks managed after cholec...
Retrieved 5 items
Total context chars: 6312
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7449
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1697

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1825
Raw output length: 8066
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'High-grade bile leaks are managed with endoscopic retrograde cholangiography and stenting (ERCS) or ...'
Answer length: 616
Final answer: 'High-grade bile leaks are managed with endoscopic retrograde cholangiography and stenting (ERCS) or ...'

Processing question 12/30: Is cholecystectomy indicated after gallstone pancr...
Retrieved 5 items
Total context chars: 5466
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6601
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1420

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1548
Raw output length: 7217
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Yes, cholecystectomy is indicated after gallstone pancreatitis. The risk of recurrent pancreatitis i...'
Answer length: 616
Final answer: 'Yes, cholecystectomy is indicated after gallstone pancreatitis. The risk of recurrent pancreatitis i...'

Processing question 13/30: What advantages does laparoscopic cholecystectomy ...
Retrieved 5 items
Total context chars: 6708
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7859
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1728

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1856
Raw output length: 8512
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy offers several advantages over open surgery, including smaller incision...'
Answer length: 652
Final answer: 'Laparoscopic cholecystectomy offers several advantages over open surgery, including smaller incision...'

Processing question 14/30: When should conversion to open cholecystectomy be ...
Retrieved 5 items
Total context chars: 5779
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6917
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1582

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1710
Raw output length: 7552
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Conversion to open cholecystectomy should be considered when the critical view of safety cannot be a...'
Answer length: 634
Final answer: 'Conversion to open cholecystectomy should be considered when the critical view of safety cannot be a...'

Processing question 15/30: Are asymptomatic gallstones an indication for chol...
Retrieved 5 items
Total context chars: 5670
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6809
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1477

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1605
Raw output length: 7497
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, asymptomatic gallstones are not an indication for cholecystectomy. The American Gastroenterologi...'
Answer length: 687
Final answer: 'No, asymptomatic gallstones are not an indication for cholecystectomy. The American Gastroenterologi...'

Processing question 16/30: How should common bile duct stones detected preope...
Retrieved 5 items
Total context chars: 5565
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6712
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1606

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1734
Raw output length: 7326
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Common bile duct stones detected preoperatively should be managed with preoperative endoscopic retro...'
Answer length: 613
Final answer: 'Common bile duct stones detected preoperatively should be managed with preoperative endoscopic retro...'

Processing question 17/30: When can patients usually resume normal activities...
Retrieved 5 items
Total context chars: 5426
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6589
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1413

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1541
Raw output length: 7202
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'
Answer length: 613
Final answer: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'

Processing question 18/30: What do SAGES guidelines say about routinely achie...
Retrieved 5 items
Total context chars: 5775
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6935
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1596

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1724
Raw output length: 7607
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'SAGES guidelines recommend routinely achieving the critical view of safety during laparoscopic chole...'
Answer length: 671
Final answer: 'SAGES guidelines recommend routinely achieving the critical view of safety during laparoscopic chole...'

Processing question 19/30: What are the most common intraoperative complicati...
Retrieved 5 items
Total context chars: 5676
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6839
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1574

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1702
Raw output length: 7451
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The most common intraoperative complications of laparoscopic cholecystectomy are bile duct injury, b...'
Answer length: 611
Final answer: 'The most common intraoperative complications of laparoscopic cholecystectomy are bile duct injury, b...'

Processing question 20/30: Is laparoscopic cholecystectomy safe during pregna...
Retrieved 5 items
Total context chars: 5552
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6683
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1543

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1671
Raw output length: 7317
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is safe during pregnancy. The procedure is performed under general anes...'
Answer length: 633
Final answer: 'Laparoscopic cholecystectomy is safe during pregnancy. The procedure is performed under general anes...'

Processing question 21/30: What constitutes the critical view of safety in la...
Retrieved 5 items
Total context chars: 5317
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6471
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1528

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1656
Raw output length: 7110
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The critical view of safety requires clearing the hepatocystic triangle of fat and tissue, separatin...'
Answer length: 639
Final answer: 'The critical view of safety requires clearing the hepatocystic triangle of fat and tissue, separatin...'

Processing question 22/30: How are postoperative bile leaks diagnosed?...
Retrieved 5 items
Total context chars: 6788
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7908
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1715

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1843
Raw output length: 8608
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Postoperative bile leaks are diagnosed by a combination of clinical presentation, laboratory finding...'
Answer length: 699
Final answer: 'Postoperative bile leaks are diagnosed by a combination of clinical presentation, laboratory finding...'

Processing question 23/30: When should intraoperative cholangiography be perf...
Retrieved 5 items
Total context chars: 6097
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7230
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1715

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1843
Raw output length: 7857
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Intraoperative cholangiography should be performed in patients with a history of gallstones, bile du...'
Answer length: 626
Final answer: 'Intraoperative cholangiography should be performed in patients with a history of gallstones, bile du...'

Processing question 24/30: How long is the typical hospital stay after uncomp...
Retrieved 5 items
Total context chars: 5610
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6774
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1547

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1675
Raw output length: 7393
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'
Answer length: 619
Final answer: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'

Processing question 25/30: Are prophylactic antibiotics required for all lapa...
Retrieved 5 items
Total context chars: 5795
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6949
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1637

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1765
Raw output length: 7558
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The SAGES Safe...'
Answer length: 608
Final answer: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The SAGES Safe...'

Processing question 26/30: Tokyo Guidelines 2018: Management strategy for Gra...
Retrieved 5 items
Total context chars: 5351
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6504
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1568

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1696
Raw output length: 7027
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend a step-up approach for the management of acute cholecystitis. Th...'
Answer length: 522
Final answer: 'The Tokyo Guidelines 2018 recommend a step-up approach for the management of acute cholecystitis. Th...'

Processing question 27/30: What is fluorescent indocyanine‑green cholangiogra...
Retrieved 5 items
Total context chars: 5501
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6652
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1608

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1736
Raw output length: 7215
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Fluorescent indocyanine‑green cholangiography (ICG-FC) is a novel technique that uses fluorescent in...'
Answer length: 563
Final answer: 'Fluorescent indocyanine‑green cholangiography (ICG-FC) is a novel technique that uses fluorescent in...'

Processing question 28/30: What is SAGES guidance on intraoperative cholangio...
Retrieved 5 items
Total context chars: 6580
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7720
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1696

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1824
Raw output length: 8332
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'SAGES recommends routine IOC in all patients undergoing laparoscopic cholecystectomy. IOC is perform...'
Answer length: 612
Final answer: 'SAGES recommends routine IOC in all patients undergoing laparoscopic cholecystectomy. IOC is perform...'

Processing question 29/30: What is the incidence of bile duct injury in lapar...
Retrieved 5 items
Total context chars: 6449
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7600
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1766

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1894
Raw output length: 8036
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The incidence of bile duct injury in laparoscopic cholecystectomy is 0.2-0.4%. The incidence of bile...'
Answer length: 435
Final answer: 'The incidence of bile duct injury in laparoscopic cholecystectomy is 0.2-0.4%. The incidence of bile...'

Processing question 30/30: How are the cystic duct and artery managed once th...
Retrieved 5 items
Total context chars: 6850
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 8005
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1727
Generated token length: 1855
Raw output length: 8598
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Once the critical view of safety is achieved, the cystic duct and cystic artery are clipped and divi...'
Answer length: 592
Final answer: 'Once the critical view of safety is achieved, the cystic duct and cystic artery are clipped and divi...'
Running combo: base_retr-none_rerank-base_gen

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Loaded 77 video segments for transcript-based retrieval

Processing question 1/30: How should the patient be positioned for laparosco...
Retrieved 5 items
Total context chars: 4841
Types: ['text', 'video', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 6004
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1293

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1421
Raw output length: 6643
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'
Answer length: 638
Final answer: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'

Processing question 2/30: What are the common indications for laparoscopic c...
Retrieved 5 items
Total context chars: 4487
Types: ['text', 'text', 'video', 'text', 'video']
System prompt length: 1032
Full prompt length: 5645
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1196

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1324
Raw output length: 6281
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The common indications for laparoscopic cholecystectomy include symptomatic gallstones, gallbladder ...'
Answer length: 636
Final answer: 'The common indications for laparoscopic cholecystectomy include symptomatic gallstones, gallbladder ...'

Processing question 3/30: Tokyo Guidelines 2018: Recommended management for ...
Retrieved 5 items
Total context chars: 5618
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 6791
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1542

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1670
Raw output length: 7435
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should undergo ...'
Answer length: 643
Final answer: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should undergo ...'

Processing question 4/30: How many laparoscopic ports are typically used, an...
Retrieved 5 items
Total context chars: 3766
Types: ['video', 'video', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 4943
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1039

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1167
Raw output length: 5573
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Typically, 4 ports are used. The camera port is placed in the port just above the umbilicus. The por...'
Answer length: 630
Final answer: 'Typically, 4 ports are used. The camera port is placed in the port just above the umbilicus. The por...'

Processing question 5/30: How does surgeon experience influence outcomes in ...
Retrieved 5 items
Total context chars: 4364
Types: ['text', 'text', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 5536
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1211

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1339
Raw output length: 6203
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. Surgeons with m...'
Answer length: 667
Final answer: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. Surgeons with m...'

Processing question 6/30: What is the standard approach if gallbladder carci...
Retrieved 5 items
Total context chars: 5909
Types: ['text', 'text', 'video', 'text', 'text']
System prompt length: 1032
Full prompt length: 7085
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1521

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1649
Raw output length: 7720
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'If gallbladders carcinoma is suspected during surgery, the standard approach is to convert to an ope...'
Answer length: 634
Final answer: 'If gallbladders carcinoma is suspected during surgery, the standard approach is to convert to an ope...'

Processing question 7/30: What are relative contraindications to laparoscopi...
Retrieved 5 items
Total context chars: 4627
Types: ['text', 'text', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 5788
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1212

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1340
Raw output length: 6349
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Relative contraindications to laparoscopic cholecystectomy include a history of Roux Y gastric bypas...'
Answer length: 561
Final answer: 'Relative contraindications to laparoscopic cholecystectomy include a history of Roux Y gastric bypas...'

Processing question 8/30: Can laparoscopic cholecystectomy be performed for ...
Retrieved 5 items
Total context chars: 5576
Types: ['text', 'text', 'video', 'text', 'text']
System prompt length: 1032
Full prompt length: 6744
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1433

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1561
Raw output length: 7322
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy can be performed for acalculous cholecystitis. The procedure is similar...'
Answer length: 578
Final answer: 'Laparoscopic cholecystectomy can be performed for acalculous cholecystitis. The procedure is similar...'

Processing question 9/30: What are the absolute contraindications to laparos...
Retrieved 5 items
Total context chars: 4627
Types: ['text', 'text', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 5792
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1213

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1341
Raw output length: 6347
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The absolute contraindications to laparoscopic cholecystectomy are a dilated common bile duct, uncer...'
Answer length: 555
Final answer: 'The absolute contraindications to laparoscopic cholecystectomy are a dilated common bile duct, uncer...'

Processing question 10/30: Tokyo Guidelines 2018: How should Grade I acute ch...
Retrieved 5 items
Total context chars: 5093
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 6259
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1492

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1620
Raw output length: 6902
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Grade I acute cholecystitis should be managed with cholecystectomy. The Tokyo Guidelines 2018 recomm...'
Answer length: 642
Final answer: 'Grade I acute cholecystitis should be managed with cholecystectomy. The Tokyo Guidelines 2018 recomm...'

Processing question 11/30: How are high‑grade bile leaks managed after cholec...
Retrieved 5 items
Total context chars: 4845
Types: ['text', 'video', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 5998
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1289

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1417
Raw output length: 6533
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'High-grade bile leaks are managed with endoscopic retrograde cholangiography and stenting (ERCP) and...'
Answer length: 534
Final answer: 'High-grade bile leaks are managed with endoscopic retrograde cholangiography and stenting (ERCP) and...'

Processing question 12/30: Is cholecystectomy indicated after gallstone pancr...
Retrieved 5 items
Total context chars: 4981
Types: ['text', 'text', 'video', 'video', 'text']
System prompt length: 1032
Full prompt length: 6132
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1325

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1453
Raw output length: 6710
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Yes, cholecystectomy is indicated after gallstone pancreatitis. The critical view of safety is impor...'
Answer length: 577
Final answer: 'Yes, cholecystectomy is indicated after gallstone pancreatitis. The critical view of safety is impor...'

Processing question 13/30: What advantages does laparoscopic cholecystectomy ...
Retrieved 5 items
Total context chars: 4627
Types: ['text', 'text', 'video', 'video', 'text']
System prompt length: 1032
Full prompt length: 5794
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1211

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1339
Raw output length: 6467
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is considered safe and is associated with fewer complications compared ...'
Answer length: 673
Final answer: 'Laparoscopic cholecystectomy is considered safe and is associated with fewer complications compared ...'

Processing question 14/30: When should conversion to open cholecystectomy be ...
Retrieved 5 items
Total context chars: 5503
Types: ['text', 'text', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 6657
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1414

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1542
Raw output length: 7276
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Conversion to open cholecystectomy should be considered in cases of bile duct injury, bile duct ston...'
Answer length: 619
Final answer: 'Conversion to open cholecystectomy should be considered in cases of bile duct injury, bile duct ston...'

Processing question 15/30: Are asymptomatic gallstones an indication for chol...
Retrieved 5 items
Total context chars: 3907
Types: ['text', 'text', 'video', 'video', 'video']
System prompt length: 1032
Full prompt length: 5062
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1100

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1228
Raw output length: 5685
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, asymptomatic gallstones are not an indication for cholecystectomy. The American Gastroenterologi...'
Answer length: 622
Final answer: 'No, asymptomatic gallstones are not an indication for cholecystectomy. The American Gastroenterologi...'

Processing question 16/30: How should common bile duct stones detected preope...
Retrieved 5 items
Total context chars: 3601
Types: ['text', 'text', 'video', 'video', 'video']
System prompt length: 1032
Full prompt length: 4764
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1023

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1151
Raw output length: 5449
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Common bile duct stones detected preoperatively should be managed with preoperative ERCP. Common bil...'
Answer length: 684
Final answer: 'Common bile duct stones detected preoperatively should be managed with preoperative ERCP. Common bil...'

Processing question 17/30: When can patients usually resume normal activities...
Retrieved 5 items
Total context chars: 5503
Types: ['text', 'video', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6682
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1418

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1546
Raw output length: 7320
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'
Answer length: 638
Final answer: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'

Processing question 18/30: What do SAGES guidelines say about routinely achie...
Retrieved 5 items
Total context chars: 4605
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 5781
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1385

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1513
Raw output length: 6448
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'SAGES guidelines recommend routinely achieving the critical view of safety during laparoscopic chole...'
Answer length: 666
Final answer: 'SAGES guidelines recommend routinely achieving the critical view of safety during laparoscopic chole...'

Processing question 19/30: What are the most common intraoperative complicati...
Retrieved 5 items
Total context chars: 5359
Types: ['text', 'video', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6538
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1448

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1576
Raw output length: 7189
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The most common intraoperative complications of laparoscopic cholecystectomy are bile duct injury, b...'
Answer length: 651
Final answer: 'The most common intraoperative complications of laparoscopic cholecystectomy are bile duct injury, b...'

Processing question 20/30: Is laparoscopic cholecystectomy safe during pregna...
Retrieved 5 items
Total context chars: 4627
Types: ['text', 'text', 'video', 'video', 'text']
System prompt length: 1032
Full prompt length: 5774
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1208

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1336
Raw output length: 6444
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is safe during pregnancy. The procedure is considered safe for pregnant...'
Answer length: 670
Final answer: 'Laparoscopic cholecystectomy is safe during pregnancy. The procedure is considered safe for pregnant...'

Processing question 21/30: What constitutes the critical view of safety in la...
Retrieved 5 items
Total context chars: 5339
Types: ['video', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6509
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1447

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1575
Raw output length: 7160
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The critical view of safety is a key principle in laparoscopic cholecystectomy that prevents bile du...'
Answer length: 651
Final answer: 'The critical view of safety is a key principle in laparoscopic cholecystectomy that prevents bile du...'

Processing question 22/30: How are postoperative bile leaks diagnosed?...
Retrieved 5 items
Total context chars: 5664
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 6800
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1440

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1568
Raw output length: 7429
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'ostoperative bile leaks are diagnosed by a combination of clinical presentation, laboratory tests, i...'
Answer length: 629
Final answer: 'ostoperative bile leaks are diagnosed by a combination of clinical presentation, laboratory tests, i...'

Processing question 23/30: When should intraoperative cholangiography be perf...
Retrieved 5 items
Total context chars: 5907
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 7056
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1530

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1658
Raw output length: 7638
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Intraoperative cholangiography should be performed when there is a dilated common bile duct, uncerta...'
Answer length: 581
Final answer: 'Intraoperative cholangiography should be performed when there is a dilated common bile duct, uncerta...'

Processing question 24/30: How long is the typical hospital stay after uncomp...
Retrieved 5 items
Total context chars: 5255
Types: ['text', 'text', 'video', 'text', 'text']
System prompt length: 1032
Full prompt length: 6435
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1437

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1565
Raw output length: 7046
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'
Answer length: 611
Final answer: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'

Processing question 25/30: Are prophylactic antibiotics required for all lapa...
Retrieved 5 items
Total context chars: 5475
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 6645
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1418

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1546
Raw output length: 7274
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The use of pro...'
Answer length: 629
Final answer: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The use of pro...'

Processing question 26/30: Tokyo Guidelines 2018: Management strategy for Gra...
Retrieved 5 items
Total context chars: 6279
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7432
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1759

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1887
Raw output length: 8129
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend a conservative treatment strategy for patients with Grade II acu...'
Answer length: 696
Final answer: 'The Tokyo Guidelines 2018 recommend a conservative treatment strategy for patients with Grade II acu...'

Processing question 27/30: What is fluorescent indocyanine‑green cholangiogra...
Retrieved 5 items
Total context chars: 5855
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 7022
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1520

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1648
Raw output length: 7572
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Fluorescent indocyanine‑green cholangiography (ICG-FC) is a novel, real-time, intraoperative imaging...'
Answer length: 550
Final answer: 'Fluorescent indocyanine‑green cholangiography (ICG-FC) is a novel, real-time, intraoperative imaging...'

Processing question 28/30: What is SAGES guidance on intraoperative cholangio...
Retrieved 5 items
Total context chars: 5973
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 7129
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1516

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1644
Raw output length: 7769
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'SAGES recommends routine IOC during laparoscopic cholecystectomy to identify bile duct stones and bi...'
Answer length: 639
Final answer: 'SAGES recommends routine IOC during laparoscopic cholecystectomy to identify bile duct stones and bi...'

Processing question 29/30: What is the incidence of bile duct injury in lapar...
Retrieved 5 items
Total context chars: 5531
Types: ['text', 'text', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 6698
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1413

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1541
Raw output length: 7230
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Bile duct injury (BDI) is the most serious complication of laparoscopic cholecystectomy. Although re...'
Answer length: 532
Final answer: 'Bile duct injury (BDI) is the most serious complication of laparoscopic cholecystectomy. Although re...'

Processing question 30/30: How are the cystic duct and artery managed once th...
Retrieved 5 items
Total context chars: 2674
Types: ['video', 'text', 'video', 'video', 'video']
System prompt length: 1032
Full prompt length: 3845
Context items: 5 (1 text, 4 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 825
Generated token length: 953
Raw output length: 4435
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Once the critical view of safety is achieved, the cystic duct and cystic artery are divided. The cys...'
Answer length: 589
Final answer: 'Once the critical view of safety is achieved, the cystic duct and cystic artery are divided. The cys...'
Running combo: base_retr-none_rerank-fine_gen

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Loaded 77 video segments for transcript-based retrieval

Processing question 1/30: How should the patient be positioned for laparosco...
Retrieved 5 items
Total context chars: 4841
Types: ['text', 'video', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 6004
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1293

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1421
Raw output length: 6643
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'
Answer length: 638
Final answer: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'

Processing question 2/30: What are the common indications for laparoscopic c...
Retrieved 5 items
Total context chars: 4487
Types: ['text', 'text', 'video', 'text', 'video']
System prompt length: 1032
Full prompt length: 5645
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1196

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1324
Raw output length: 6281
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The common indications for laparoscopic cholecystectomy include symptomatic gallstones, gallbladder ...'
Answer length: 636
Final answer: 'The common indications for laparoscopic cholecystectomy include symptomatic gallstones, gallbladder ...'

Processing question 3/30: Tokyo Guidelines 2018: Recommended management for ...
Retrieved 5 items
Total context chars: 5618
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 6791
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1542

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1670
Raw output length: 7435
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should undergo ...'
Answer length: 643
Final answer: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should undergo ...'

Processing question 4/30: How many laparoscopic ports are typically used, an...
Retrieved 5 items
Total context chars: 3766
Types: ['video', 'video', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 4943
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1039

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1167
Raw output length: 5573
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Typically, 4 ports are used. The camera port is placed in the port just above the umbilicus. The por...'
Answer length: 630
Final answer: 'Typically, 4 ports are used. The camera port is placed in the port just above the umbilicus. The por...'

Processing question 5/30: How does surgeon experience influence outcomes in ...
Retrieved 5 items
Total context chars: 4364
Types: ['text', 'text', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 5536
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1211

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1339
Raw output length: 6203
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. Surgeons with m...'
Answer length: 667
Final answer: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. Surgeons with m...'

Processing question 6/30: What is the standard approach if gallbladder carci...
Retrieved 5 items
Total context chars: 5909
Types: ['text', 'text', 'video', 'text', 'text']
System prompt length: 1032
Full prompt length: 7085
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1521

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1649
Raw output length: 7720
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'If gallbladders carcinoma is suspected during surgery, the standard approach is to convert to an ope...'
Answer length: 634
Final answer: 'If gallbladders carcinoma is suspected during surgery, the standard approach is to convert to an ope...'

Processing question 7/30: What are relative contraindications to laparoscopi...
Retrieved 5 items
Total context chars: 4627
Types: ['text', 'text', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 5788
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1212

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1340
Raw output length: 6349
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Relative contraindications to laparoscopic cholecystectomy include a history of Roux Y gastric bypas...'
Answer length: 561
Final answer: 'Relative contraindications to laparoscopic cholecystectomy include a history of Roux Y gastric bypas...'

Processing question 8/30: Can laparoscopic cholecystectomy be performed for ...
Retrieved 5 items
Total context chars: 5576
Types: ['text', 'text', 'video', 'text', 'text']
System prompt length: 1032
Full prompt length: 6744
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1433

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1561
Raw output length: 7322
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy can be performed for acalculous cholecystitis. The procedure is similar...'
Answer length: 578
Final answer: 'Laparoscopic cholecystectomy can be performed for acalculous cholecystitis. The procedure is similar...'

Processing question 9/30: What are the absolute contraindications to laparos...
Retrieved 5 items
Total context chars: 4627
Types: ['text', 'text', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 5792
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1213

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1341
Raw output length: 6347
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The absolute contraindications to laparoscopic cholecystectomy are a dilated common bile duct, uncer...'
Answer length: 555
Final answer: 'The absolute contraindications to laparoscopic cholecystectomy are a dilated common bile duct, uncer...'

Processing question 10/30: Tokyo Guidelines 2018: How should Grade I acute ch...
Retrieved 5 items
Total context chars: 5093
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 6259
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1492

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1620
Raw output length: 6902
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Grade I acute cholecystitis should be managed with cholecystectomy. The Tokyo Guidelines 2018 recomm...'
Answer length: 642
Final answer: 'Grade I acute cholecystitis should be managed with cholecystectomy. The Tokyo Guidelines 2018 recomm...'

Processing question 11/30: How are high‑grade bile leaks managed after cholec...
Retrieved 5 items
Total context chars: 4845
Types: ['text', 'video', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 5998
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1289

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1417
Raw output length: 6533
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'High-grade bile leaks are managed with endoscopic retrograde cholangiography and stenting (ERCP) and...'
Answer length: 534
Final answer: 'High-grade bile leaks are managed with endoscopic retrograde cholangiography and stenting (ERCP) and...'

Processing question 12/30: Is cholecystectomy indicated after gallstone pancr...
Retrieved 5 items
Total context chars: 4981
Types: ['text', 'text', 'video', 'video', 'text']
System prompt length: 1032
Full prompt length: 6132
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1325

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1453
Raw output length: 6710
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Yes, cholecystectomy is indicated after gallstone pancreatitis. The critical view of safety is impor...'
Answer length: 577
Final answer: 'Yes, cholecystectomy is indicated after gallstone pancreatitis. The critical view of safety is impor...'

Processing question 13/30: What advantages does laparoscopic cholecystectomy ...
Retrieved 5 items
Total context chars: 4627
Types: ['text', 'text', 'video', 'video', 'text']
System prompt length: 1032
Full prompt length: 5794
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1211

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1339
Raw output length: 6467
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is considered safe and is associated with fewer complications compared ...'
Answer length: 673
Final answer: 'Laparoscopic cholecystectomy is considered safe and is associated with fewer complications compared ...'

Processing question 14/30: When should conversion to open cholecystectomy be ...
Retrieved 5 items
Total context chars: 5503
Types: ['text', 'text', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 6657
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1414

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1542
Raw output length: 7276
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Conversion to open cholecystectomy should be considered in cases of bile duct injury, bile duct ston...'
Answer length: 619
Final answer: 'Conversion to open cholecystectomy should be considered in cases of bile duct injury, bile duct ston...'

Processing question 15/30: Are asymptomatic gallstones an indication for chol...
Retrieved 5 items
Total context chars: 3907
Types: ['text', 'text', 'video', 'video', 'video']
System prompt length: 1032
Full prompt length: 5062
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1100

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1228
Raw output length: 5685
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, asymptomatic gallstones are not an indication for cholecystectomy. The American Gastroenterologi...'
Answer length: 622
Final answer: 'No, asymptomatic gallstones are not an indication for cholecystectomy. The American Gastroenterologi...'

Processing question 16/30: How should common bile duct stones detected preope...
Retrieved 5 items
Total context chars: 3601
Types: ['text', 'text', 'video', 'video', 'video']
System prompt length: 1032
Full prompt length: 4764
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1023

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1151
Raw output length: 5449
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Common bile duct stones detected preoperatively should be managed with preoperative ERCP. Common bil...'
Answer length: 684
Final answer: 'Common bile duct stones detected preoperatively should be managed with preoperative ERCP. Common bil...'

Processing question 17/30: When can patients usually resume normal activities...
Retrieved 5 items
Total context chars: 5503
Types: ['text', 'video', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6682
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1418

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1546
Raw output length: 7320
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'
Answer length: 638
Final answer: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'

Processing question 18/30: What do SAGES guidelines say about routinely achie...
Retrieved 5 items
Total context chars: 4605
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 5781
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1385

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1513
Raw output length: 6448
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'SAGES guidelines recommend routinely achieving the critical view of safety during laparoscopic chole...'
Answer length: 666
Final answer: 'SAGES guidelines recommend routinely achieving the critical view of safety during laparoscopic chole...'

Processing question 19/30: What are the most common intraoperative complicati...
Retrieved 5 items
Total context chars: 5359
Types: ['text', 'video', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6538
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1448

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1576
Raw output length: 7189
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The most common intraoperative complications of laparoscopic cholecystectomy are bile duct injury, b...'
Answer length: 651
Final answer: 'The most common intraoperative complications of laparoscopic cholecystectomy are bile duct injury, b...'

Processing question 20/30: Is laparoscopic cholecystectomy safe during pregna...
Retrieved 5 items
Total context chars: 4627
Types: ['text', 'text', 'video', 'video', 'text']
System prompt length: 1032
Full prompt length: 5774
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1208

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1336
Raw output length: 6444
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is safe during pregnancy. The procedure is considered safe for pregnant...'
Answer length: 670
Final answer: 'Laparoscopic cholecystectomy is safe during pregnancy. The procedure is considered safe for pregnant...'

Processing question 21/30: What constitutes the critical view of safety in la...
Retrieved 5 items
Total context chars: 5339
Types: ['video', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6509
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1447

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1575
Raw output length: 7160
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The critical view of safety is a key principle in laparoscopic cholecystectomy that prevents bile du...'
Answer length: 651
Final answer: 'The critical view of safety is a key principle in laparoscopic cholecystectomy that prevents bile du...'

Processing question 22/30: How are postoperative bile leaks diagnosed?...
Retrieved 5 items
Total context chars: 5664
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 6800
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1440

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1568
Raw output length: 7429
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'ostoperative bile leaks are diagnosed by a combination of clinical presentation, laboratory tests, i...'
Answer length: 629
Final answer: 'ostoperative bile leaks are diagnosed by a combination of clinical presentation, laboratory tests, i...'

Processing question 23/30: When should intraoperative cholangiography be perf...
Retrieved 5 items
Total context chars: 5907
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 7056
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1530

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1658
Raw output length: 7638
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Intraoperative cholangiography should be performed when there is a dilated common bile duct, uncerta...'
Answer length: 581
Final answer: 'Intraoperative cholangiography should be performed when there is a dilated common bile duct, uncerta...'

Processing question 24/30: How long is the typical hospital stay after uncomp...
Retrieved 5 items
Total context chars: 5255
Types: ['text', 'text', 'video', 'text', 'text']
System prompt length: 1032
Full prompt length: 6435
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1437

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1565
Raw output length: 7046
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'
Answer length: 611
Final answer: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'

Processing question 25/30: Are prophylactic antibiotics required for all lapa...
Retrieved 5 items
Total context chars: 5475
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 6645
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1418

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1546
Raw output length: 7274
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The use of pro...'
Answer length: 629
Final answer: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The use of pro...'

Processing question 26/30: Tokyo Guidelines 2018: Management strategy for Gra...
Retrieved 5 items
Total context chars: 6279
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7432
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1759

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1887
Raw output length: 8129
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend a conservative treatment strategy for patients with Grade II acu...'
Answer length: 696
Final answer: 'The Tokyo Guidelines 2018 recommend a conservative treatment strategy for patients with Grade II acu...'

Processing question 27/30: What is fluorescent indocyanine‑green cholangiogra...
Retrieved 5 items
Total context chars: 5855
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 7022
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1520

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1648
Raw output length: 7572
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Fluorescent indocyanine‑green cholangiography (ICG-FC) is a novel, real-time, intraoperative imaging...'
Answer length: 550
Final answer: 'Fluorescent indocyanine‑green cholangiography (ICG-FC) is a novel, real-time, intraoperative imaging...'

Processing question 28/30: What is SAGES guidance on intraoperative cholangio...
Retrieved 5 items
Total context chars: 5973
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 7129
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1516

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1644
Raw output length: 7769
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'SAGES recommends routine IOC during laparoscopic cholecystectomy to identify bile duct stones and bi...'
Answer length: 639
Final answer: 'SAGES recommends routine IOC during laparoscopic cholecystectomy to identify bile duct stones and bi...'

Processing question 29/30: What is the incidence of bile duct injury in lapar...
Retrieved 5 items
Total context chars: 5531
Types: ['text', 'text', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 6698
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1413

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1541
Raw output length: 7230
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Bile duct injury (BDI) is the most serious complication of laparoscopic cholecystectomy. Although re...'
Answer length: 532
Final answer: 'Bile duct injury (BDI) is the most serious complication of laparoscopic cholecystectomy. Although re...'

Processing question 30/30: How are the cystic duct and artery managed once th...
Retrieved 5 items
Total context chars: 2674
Types: ['video', 'text', 'video', 'video', 'video']
System prompt length: 1032
Full prompt length: 3845
Context items: 5 (1 text, 4 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 825
Generated token length: 953
Raw output length: 4435
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Once the critical view of safety is achieved, the cystic duct and cystic artery are divided. The cys...'
Answer length: 589
Final answer: 'Once the critical view of safety is achieved, the cystic duct and cystic artery are divided. The cys...'
Running combo: base_retr-cross_rerank-base_gen
Loaded 77 video segments for transcript-based retrieval

Processing question 1/30: How should the patient be positioned for laparosco...

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Retrieved 5 items
Total context chars: 5735
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 6898
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1501

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1629
Raw output length: 7544
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'
Answer length: 645
Final answer: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'

Processing question 2/30: What are the common indications for laparoscopic c...
Retrieved 5 items
Total context chars: 4515
Types: ['text', 'text', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 5673
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1215

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1343
Raw output length: 6289
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The most common indications for laparoscopic cholecystectomy are symptomatic gallstones, gallbladder...'
Answer length: 616
Final answer: 'The most common indications for laparoscopic cholecystectomy are symptomatic gallstones, gallbladder...'

Processing question 3/30: Tokyo Guidelines 2018: Recommended management for ...
Retrieved 5 items
Total context chars: 6811
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7968
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1747

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1875
Raw output length: 8668
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should be treat...'
Answer length: 699
Final answer: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should be treat...'

Processing question 4/30: How many laparoscopic ports are typically used, an...
Retrieved 5 items
Total context chars: 3969
Types: ['text', 'video', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 5146
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1146

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1274
Raw output length: 5645
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Typically, 4 ports are used in laparoscopic cholecystectomy. The camera port is placed in the T1 pos...'
Answer length: 498
Final answer: 'Typically, 4 ports are used in laparoscopic cholecystectomy. The camera port is placed in the T1 pos...'

Processing question 5/30: How does surgeon experience influence outcomes in ...
Retrieved 5 items
Total context chars: 5206
Types: ['text', 'video', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6378
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1448

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1576
Raw output length: 7042
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. Studies have sh...'
Answer length: 664
Final answer: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. Studies have sh...'

Processing question 6/30: What is the standard approach if gallbladder carci...
Retrieved 5 items
Total context chars: 5927
Types: ['video', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7103
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1495

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1623
Raw output length: 7738
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'If gallbladders carcinoma is suspected during surgery, the standard approach is to convert to an ope...'
Answer length: 634
Final answer: 'If gallbladders carcinoma is suspected during surgery, the standard approach is to convert to an ope...'

Processing question 7/30: What are relative contraindications to laparoscopi...
Retrieved 5 items
Total context chars: 6438
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7583
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1635

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1763
Raw output length: 8272
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Relative contraindications to laparoscopic cholecystectomy include severe obesity, previous upper ab...'
Answer length: 689
Final answer: 'Relative contraindications to laparoscopic cholecystectomy include severe obesity, previous upper ab...'

Processing question 8/30: Can laparoscopic cholecystectomy be performed for ...
Retrieved 5 items
Total context chars: 6438
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7590
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1639

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1767
Raw output length: 8138
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is the treatment of choice for acalculous cholecystitis. It is safe and...'
Answer length: 548
Final answer: 'Laparoscopic cholecystectomy is the treatment of choice for acalculous cholecystitis. It is safe and...'

Processing question 9/30: What are the absolute contraindications to laparos...
Retrieved 5 items
Total context chars: 6438
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7587
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1636

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1764
Raw output length: 8226
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'There are no absolute contraindications to laparoscopic cholecystectomy. However, certain conditions...'
Answer length: 639
Final answer: 'There are no absolute contraindications to laparoscopic cholecystectomy. However, certain conditions...'

Processing question 10/30: Tokyo Guidelines 2018: How should Grade I acute ch...
Retrieved 5 items
Total context chars: 6796
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7946
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1731

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1859
Raw output length: 8600
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Grade I acute cholecystitis is characterized by mild symptoms and no signs of pericholecystic fluid....'
Answer length: 653
Final answer: 'Grade I acute cholecystitis is characterized by mild symptoms and no signs of pericholecystic fluid....'

Processing question 11/30: How are high‑grade bile leaks managed after cholec...
Retrieved 5 items
Total context chars: 5816
Types: ['text', 'video', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6969
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1511

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1639
Raw output length: 7506
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'High-grade bile leaks are managed with endoscopic retrograde cholangiography and stenting (ERCS) or ...'
Answer length: 536
Final answer: 'High-grade bile leaks are managed with endoscopic retrograde cholangiography and stenting (ERCS) or ...'

Processing question 12/30: Is cholecystectomy indicated after gallstone pancr...
Retrieved 5 items
Total context chars: 6457
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7592
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1756

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1884
Raw output length: 8147
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Cholecystectomy is indicated after gallstone pancreatitis. The most common complication of laparosco...'
Answer length: 555
Final answer: 'Cholecystectomy is indicated after gallstone pancreatitis. The most common complication of laparosco...'

Processing question 13/30: What advantages does laparoscopic cholecystectomy ...
Retrieved 5 items
Total context chars: 5531
Types: ['video', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6698
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1428

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1556
Raw output length: 7308
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy offers several advantages over open surgery, including reduced cost, sh...'
Answer length: 610
Final answer: 'Laparoscopic cholecystectomy offers several advantages over open surgery, including reduced cost, sh...'

Processing question 14/30: When should conversion to open cholecystectomy be ...
Retrieved 5 items
Total context chars: 5422
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 6576
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1422

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1550
Raw output length: 7219
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Conversion to open cholecystectomy should be considered when the surgeon is unable to safely complet...'
Answer length: 643
Final answer: 'Conversion to open cholecystectomy should be considered when the surgeon is unable to safely complet...'

Processing question 15/30: Are asymptomatic gallstones an indication for chol...
Retrieved 5 items
Total context chars: 6490
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7629
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1751

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1879
Raw output length: 8310
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, asymptomatic gallstones are not an indication for cholecystectomy. In fact, the American Gastroe...'
Answer length: 680
Final answer: 'No, asymptomatic gallstones are not an indication for cholecystectomy. In fact, the American Gastroe...'

Processing question 16/30: How should common bile duct stones detected preope...
Retrieved 5 items
Total context chars: 6809
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7956
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1725

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1853
Raw output length: 8641
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Common bile duct stones detected preoperatively should be managed with preoperative ERCP. Common bil...'
Answer length: 684
Final answer: 'Common bile duct stones detected preoperatively should be managed with preoperative ERCP. Common bil...'

Processing question 17/30: When can patients usually resume normal activities...
Retrieved 5 items
Total context chars: 6438
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7601
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1635

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1763
Raw output length: 8273
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'
Answer length: 672
Final answer: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'

Processing question 18/30: What do SAGES guidelines say about routinely achie...
Retrieved 5 items
Total context chars: 4803
Types: ['text', 'text', 'video', 'text', 'text']
System prompt length: 1032
Full prompt length: 5979
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1319

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1447
Raw output length: 6638
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Society of American Gastrointestinal and Endoscopic Surgeons (SAGES) Safe Cholecystectomy Progra...'
Answer length: 659
Final answer: 'The Society of American Gastrointestinal and Endoscopic Surgeons (SAGES) Safe Cholecystectomy Progra...'

Processing question 19/30: What are the most common intraoperative complicati...
Retrieved 5 items
Total context chars: 6142
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7305
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1642

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1770
Raw output length: 7953
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The most common intraoperative complications of laparoscopic cholecystectomy are bleeding, abscess, ...'
Answer length: 648
Final answer: 'The most common intraoperative complications of laparoscopic cholecystectomy are bleeding, abscess, ...'

Processing question 20/30: Is laparoscopic cholecystectomy safe during pregna...
Retrieved 5 items
Total context chars: 6463
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7594
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1631

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1759
Raw output length: 8324
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is safe during pregnancy. The procedure is considered safe for pregnant...'
Answer length: 730
Final answer: 'Laparoscopic cholecystectomy is safe during pregnancy. The procedure is considered safe for pregnant...'

Processing question 21/30: What constitutes the critical view of safety in la...
Retrieved 5 items
Total context chars: 5627
Types: ['text', 'text', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 6797
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1441

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1569
Raw output length: 7402
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The critical view of safety is a key principle of safe laparoscopic cholecystectomy. It requires cle...'
Answer length: 605
Final answer: 'The critical view of safety is a key principle of safe laparoscopic cholecystectomy. It requires cle...'

Processing question 22/30: How are postoperative bile leaks diagnosed?...
Retrieved 5 items
Total context chars: 5797
Types: ['text', 'video', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6933
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1509

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1637
Raw output length: 7573
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Postoperative bile leaks are diagnosed by a combination of clinical presentation, imaging studies, a...'
Answer length: 640
Final answer: 'Postoperative bile leaks are diagnosed by a combination of clinical presentation, imaging studies, a...'

Processing question 23/30: When should intraoperative cholangiography be perf...
Retrieved 5 items
Total context chars: 6556
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7689
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1721

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1849
Raw output length: 8250
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Intraoperative cholangiography should be performed when there is a dilated common bile duct, uncerta...'
Answer length: 560
Final answer: 'Intraoperative cholangiography should be performed when there is a dilated common bile duct, uncerta...'

Processing question 24/30: How long is the typical hospital stay after uncomp...
Retrieved 5 items
Total context chars: 6438
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7602
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1637

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1765
Raw output length: 8225
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'
Answer length: 623
Final answer: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'

Processing question 25/30: Are prophylactic antibiotics required for all lapa...
Retrieved 5 items
Total context chars: 6438
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7592
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1637

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1765
Raw output length: 8201
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The decision t...'
Answer length: 609
Final answer: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The decision t...'

Processing question 26/30: Tokyo Guidelines 2018: Management strategy for Gra...
Retrieved 5 items
Total context chars: 6796
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7949
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1730

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1858
Raw output length: 8666
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend a conservative treatment strategy for patients with Grade II acu...'
Answer length: 716
Final answer: 'The Tokyo Guidelines 2018 recommend a conservative treatment strategy for patients with Grade II acu...'

Processing question 27/30: What is fluorescent indocyanine‑green cholangiogra...
Retrieved 5 items
Total context chars: 6575
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7726
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1735

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1863
Raw output length: 8254
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Fluorescent indocyanine‑green cholangiography (ICG-FC) is a novel, real-time, intraoperative imaging...'
Answer length: 528
Final answer: 'Fluorescent indocyanine‑green cholangiography (ICG-FC) is a novel, real-time, intraoperative imaging...'

Processing question 28/30: What is SAGES guidance on intraoperative cholangio...
Retrieved 5 items
Total context chars: 6519
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7659
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1626

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1754
Raw output length: 8333
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'SAGES recommends performing IOC in all patients undergoing laparoscopic cholecystectomy. The authors...'
Answer length: 674
Final answer: 'SAGES recommends performing IOC in all patients undergoing laparoscopic cholecystectomy. The authors...'

Processing question 29/30: What is the incidence of bile duct injury in lapar...
Retrieved 5 items
Total context chars: 6142
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7293
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1642

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1770
Raw output length: 7870
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Bile duct injury (BDI) is the most serious complication of laparoscopic cholecystectomy and occurs i...'
Answer length: 577
Final answer: 'Bile duct injury (BDI) is the most serious complication of laparoscopic cholecystectomy and occurs i...'

Processing question 30/30: How are the cystic duct and artery managed once th...
Retrieved 5 items
Total context chars: 4824
Types: ['text', 'video', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 5995
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1322
Generated token length: 1450
Raw output length: 6541
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Once the critical view of safety is established, the cystic artery is clipped and divided. The cysti...'
Answer length: 545
Final answer: 'Once the critical view of safety is established, the cystic artery is clipped and divided. The cysti...'
Running combo: base_retr-cross_rerank-fine_gen
Loaded 77 video segments for transcript-based retrieval

Processing question 1/30: How should the patient be positioned for laparosco...
Retrieved 5 items
Total context chars: 5735
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 6898
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Input token length: 1501

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1629
Raw output length: 7544
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'
Answer length: 645
Final answer: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'

Processing question 2/30: What are the common indications for laparoscopic c...
Retrieved 5 items
Total context chars: 4515
Types: ['text', 'text', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 5673
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1215

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1343
Raw output length: 6289
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The most common indications for laparoscopic cholecystectomy are symptomatic gallstones, gallbladder...'
Answer length: 616
Final answer: 'The most common indications for laparoscopic cholecystectomy are symptomatic gallstones, gallbladder...'

Processing question 3/30: Tokyo Guidelines 2018: Recommended management for ...
Retrieved 5 items
Total context chars: 6811
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7968
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1747

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1875
Raw output length: 8668
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should be treat...'
Answer length: 699
Final answer: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should be treat...'

Processing question 4/30: How many laparoscopic ports are typically used, an...
Retrieved 5 items
Total context chars: 3969
Types: ['text', 'video', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 5146
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1146

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1274
Raw output length: 5645
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Typically, 4 ports are used in laparoscopic cholecystectomy. The camera port is placed in the T1 pos...'
Answer length: 498
Final answer: 'Typically, 4 ports are used in laparoscopic cholecystectomy. The camera port is placed in the T1 pos...'

Processing question 5/30: How does surgeon experience influence outcomes in ...
Retrieved 5 items
Total context chars: 5206
Types: ['text', 'video', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6378
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1448

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1576
Raw output length: 7042
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. Studies have sh...'
Answer length: 664
Final answer: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. Studies have sh...'

Processing question 6/30: What is the standard approach if gallbladder carci...
Retrieved 5 items
Total context chars: 5927
Types: ['video', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7103
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1495

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1623
Raw output length: 7738
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'If gallbladders carcinoma is suspected during surgery, the standard approach is to convert to an ope...'
Answer length: 634
Final answer: 'If gallbladders carcinoma is suspected during surgery, the standard approach is to convert to an ope...'

Processing question 7/30: What are relative contraindications to laparoscopi...
Retrieved 5 items
Total context chars: 6438
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7583
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1635

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1763
Raw output length: 8272
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Relative contraindications to laparoscopic cholecystectomy include severe obesity, previous upper ab...'
Answer length: 689
Final answer: 'Relative contraindications to laparoscopic cholecystectomy include severe obesity, previous upper ab...'

Processing question 8/30: Can laparoscopic cholecystectomy be performed for ...
Retrieved 5 items
Total context chars: 6438
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7590
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1639

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1767
Raw output length: 8138
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is the treatment of choice for acalculous cholecystitis. It is safe and...'
Answer length: 548
Final answer: 'Laparoscopic cholecystectomy is the treatment of choice for acalculous cholecystitis. It is safe and...'

Processing question 9/30: What are the absolute contraindications to laparos...
Retrieved 5 items
Total context chars: 6438
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7587
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1636

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1764
Raw output length: 8226
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'There are no absolute contraindications to laparoscopic cholecystectomy. However, certain conditions...'
Answer length: 639
Final answer: 'There are no absolute contraindications to laparoscopic cholecystectomy. However, certain conditions...'

Processing question 10/30: Tokyo Guidelines 2018: How should Grade I acute ch...
Retrieved 5 items
Total context chars: 6796
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7946
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1731

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1859
Raw output length: 8600
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Grade I acute cholecystitis is characterized by mild symptoms and no signs of pericholecystic fluid....'
Answer length: 653
Final answer: 'Grade I acute cholecystitis is characterized by mild symptoms and no signs of pericholecystic fluid....'

Processing question 11/30: How are high‑grade bile leaks managed after cholec...
Retrieved 5 items
Total context chars: 5816
Types: ['text', 'video', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6969
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1511

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1639
Raw output length: 7506
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'High-grade bile leaks are managed with endoscopic retrograde cholangiography and stenting (ERCS) or ...'
Answer length: 536
Final answer: 'High-grade bile leaks are managed with endoscopic retrograde cholangiography and stenting (ERCS) or ...'

Processing question 12/30: Is cholecystectomy indicated after gallstone pancr...
Retrieved 5 items
Total context chars: 6457
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7592
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1756

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1884
Raw output length: 8147
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Cholecystectomy is indicated after gallstone pancreatitis. The most common complication of laparosco...'
Answer length: 555
Final answer: 'Cholecystectomy is indicated after gallstone pancreatitis. The most common complication of laparosco...'

Processing question 13/30: What advantages does laparoscopic cholecystectomy ...
Retrieved 5 items
Total context chars: 5531
Types: ['video', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6698
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1428

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1556
Raw output length: 7308
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy offers several advantages over open surgery, including reduced cost, sh...'
Answer length: 610
Final answer: 'Laparoscopic cholecystectomy offers several advantages over open surgery, including reduced cost, sh...'

Processing question 14/30: When should conversion to open cholecystectomy be ...
Retrieved 5 items
Total context chars: 5422
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 6576
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1422

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1550
Raw output length: 7219
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Conversion to open cholecystectomy should be considered when the surgeon is unable to safely complet...'
Answer length: 643
Final answer: 'Conversion to open cholecystectomy should be considered when the surgeon is unable to safely complet...'

Processing question 15/30: Are asymptomatic gallstones an indication for chol...
Retrieved 5 items
Total context chars: 6490
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7629
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1751

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1879
Raw output length: 8310
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, asymptomatic gallstones are not an indication for cholecystectomy. In fact, the American Gastroe...'
Answer length: 680
Final answer: 'No, asymptomatic gallstones are not an indication for cholecystectomy. In fact, the American Gastroe...'

Processing question 16/30: How should common bile duct stones detected preope...
Retrieved 5 items
Total context chars: 6809
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7956
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1725

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1853
Raw output length: 8641
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Common bile duct stones detected preoperatively should be managed with preoperative ERCP. Common bil...'
Answer length: 684
Final answer: 'Common bile duct stones detected preoperatively should be managed with preoperative ERCP. Common bil...'

Processing question 17/30: When can patients usually resume normal activities...
Retrieved 5 items
Total context chars: 6438
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7601
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1635

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1763
Raw output length: 8273
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'
Answer length: 672
Final answer: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'

Processing question 18/30: What do SAGES guidelines say about routinely achie...
Retrieved 5 items
Total context chars: 4803
Types: ['text', 'text', 'video', 'text', 'text']
System prompt length: 1032
Full prompt length: 5979
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1319

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1447
Raw output length: 6638
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Society of American Gastrointestinal and Endoscopic Surgeons (SAGES) Safe Cholecystectomy Progra...'
Answer length: 659
Final answer: 'The Society of American Gastrointestinal and Endoscopic Surgeons (SAGES) Safe Cholecystectomy Progra...'

Processing question 19/30: What are the most common intraoperative complicati...
Retrieved 5 items
Total context chars: 6142
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7305
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1642

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1770
Raw output length: 7953
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The most common intraoperative complications of laparoscopic cholecystectomy are bleeding, abscess, ...'
Answer length: 648
Final answer: 'The most common intraoperative complications of laparoscopic cholecystectomy are bleeding, abscess, ...'

Processing question 20/30: Is laparoscopic cholecystectomy safe during pregna...
Retrieved 5 items
Total context chars: 6463
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7594
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1631

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1759
Raw output length: 8324
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is safe during pregnancy. The procedure is considered safe for pregnant...'
Answer length: 730
Final answer: 'Laparoscopic cholecystectomy is safe during pregnancy. The procedure is considered safe for pregnant...'

Processing question 21/30: What constitutes the critical view of safety in la...
Retrieved 5 items
Total context chars: 5627
Types: ['text', 'text', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 6797
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1441

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1569
Raw output length: 7402
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The critical view of safety is a key principle of safe laparoscopic cholecystectomy. It requires cle...'
Answer length: 605
Final answer: 'The critical view of safety is a key principle of safe laparoscopic cholecystectomy. It requires cle...'

Processing question 22/30: How are postoperative bile leaks diagnosed?...
Retrieved 5 items
Total context chars: 5797
Types: ['text', 'video', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6933
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1509

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1637
Raw output length: 7573
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Postoperative bile leaks are diagnosed by a combination of clinical presentation, imaging studies, a...'
Answer length: 640
Final answer: 'Postoperative bile leaks are diagnosed by a combination of clinical presentation, imaging studies, a...'

Processing question 23/30: When should intraoperative cholangiography be perf...
Retrieved 5 items
Total context chars: 6556
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7689
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1721

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1849
Raw output length: 8250
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Intraoperative cholangiography should be performed when there is a dilated common bile duct, uncerta...'
Answer length: 560
Final answer: 'Intraoperative cholangiography should be performed when there is a dilated common bile duct, uncerta...'

Processing question 24/30: How long is the typical hospital stay after uncomp...
Retrieved 5 items
Total context chars: 6438
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7602
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1637

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1765
Raw output length: 8225
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'
Answer length: 623
Final answer: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'

Processing question 25/30: Are prophylactic antibiotics required for all lapa...
Retrieved 5 items
Total context chars: 6438
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7592
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1637

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1765
Raw output length: 8201
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The decision t...'
Answer length: 609
Final answer: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The decision t...'

Processing question 26/30: Tokyo Guidelines 2018: Management strategy for Gra...
Retrieved 5 items
Total context chars: 6796
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7949
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1730

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1858
Raw output length: 8666
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend a conservative treatment strategy for patients with Grade II acu...'
Answer length: 716
Final answer: 'The Tokyo Guidelines 2018 recommend a conservative treatment strategy for patients with Grade II acu...'

Processing question 27/30: What is fluorescent indocyanine‑green cholangiogra...
Retrieved 5 items
Total context chars: 6575
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7726
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1735

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1863
Raw output length: 8254
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Fluorescent indocyanine‑green cholangiography (ICG-FC) is a novel, real-time, intraoperative imaging...'
Answer length: 528
Final answer: 'Fluorescent indocyanine‑green cholangiography (ICG-FC) is a novel, real-time, intraoperative imaging...'

Processing question 28/30: What is SAGES guidance on intraoperative cholangio...
Retrieved 5 items
Total context chars: 6519
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7659
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1626

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1754
Raw output length: 8333
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'SAGES recommends performing IOC in all patients undergoing laparoscopic cholecystectomy. The authors...'
Answer length: 674
Final answer: 'SAGES recommends performing IOC in all patients undergoing laparoscopic cholecystectomy. The authors...'

Processing question 29/30: What is the incidence of bile duct injury in lapar...
Retrieved 5 items
Total context chars: 6142
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7293
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1642

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1770
Raw output length: 7870
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Bile duct injury (BDI) is the most serious complication of laparoscopic cholecystectomy and occurs i...'
Answer length: 577
Final answer: 'Bile duct injury (BDI) is the most serious complication of laparoscopic cholecystectomy and occurs i...'

Processing question 30/30: How are the cystic duct and artery managed once th...
Retrieved 5 items
Total context chars: 4824
Types: ['text', 'video', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 5995
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1322
Generated token length: 1450
Raw output length: 6541
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Once the critical view of safety is established, the cystic artery is clipped and divided. The cysti...'
Answer length: 545
Final answer: 'Once the critical view of safety is established, the cystic artery is clipped and divided. The cysti...'
Running combo: fine_retr-none_rerank-base_gen
Total chunks: 19
Embeddings tensor shape: torch.Size([19, 768])
Building exact IndexFlatIP …
Index built with 19 vectors  |  dim = 768

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Loaded 77 video segments for transcript-based retrieval

Processing question 1/30: How should the patient be positioned for laparosco...
Retrieved 5 items
Total context chars: 5661
Types: ['text', 'video', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6824
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1523

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1651
Raw output length: 7463
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'
Answer length: 638
Final answer: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'

Processing question 2/30: What are the common indications for laparoscopic c...
Retrieved 5 items
Total context chars: 4833
Types: ['text', 'text', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 5991
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1246

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1374
Raw output length: 6579
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The common indications for laparoscopic cholecystectomy include symptomatic gallstones, gallbladder ...'
Answer length: 588
Final answer: 'The common indications for laparoscopic cholecystectomy include symptomatic gallstones, gallbladder ...'

Processing question 3/30: Tokyo Guidelines 2018: Recommended management for ...
Retrieved 5 items
Total context chars: 4958
Types: ['text', 'text', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 6131
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1468

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1596
Raw output length: 6817
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should undergo ...'
Answer length: 686
Final answer: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should undergo ...'

Processing question 4/30: How many laparoscopic ports are typically used, an...
Retrieved 5 items
Total context chars: 1722
Types: ['video', 'video', 'video', 'video', 'video']
System prompt length: 1032
Full prompt length: 2885
Context items: 5 (0 text, 5 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 634

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 762
Raw output length: 3489
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Four ports are typically used. The camera port is 10mm and is placed in the supra umbilical region. ...'
Answer length: 604
Final answer: 'Four ports are typically used. The camera port is 10mm and is placed in the supra umbilical region. ...'

Processing question 5/30: How does surgeon experience influence outcomes in ...
Retrieved 5 items
Total context chars: 5206
Types: ['text', 'text', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 6378
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1465

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1593
Raw output length: 7029
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. Studies have sh...'
Answer length: 651
Final answer: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. Studies have sh...'

Processing question 6/30: What is the standard approach if gallbladder carci...
Retrieved 5 items
Total context chars: 4171
Types: ['text', 'video', 'video', 'text', 'video']
System prompt length: 1032
Full prompt length: 5347
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1144

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1272
Raw output length: 5981
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'If gallbladdar carcinoma is suspected during surgery, the standard approach is to convert to an open...'
Answer length: 633
Final answer: 'If gallbladdar carcinoma is suspected during surgery, the standard approach is to convert to an open...'

Processing question 7/30: What are relative contraindications to laparoscopi...
Retrieved 5 items
Total context chars: 5540
Types: ['text', 'text', 'video', 'text', 'text']
System prompt length: 1032
Full prompt length: 6701
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1424

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1552
Raw output length: 7281
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Relative contraindications to laparoscopic cholecystectomy include a history of Roux Y gastric bypas...'
Answer length: 580
Final answer: 'Relative contraindications to laparoscopic cholecystectomy include a history of Roux Y gastric bypas...'

Processing question 8/30: Can laparoscopic cholecystectomy be performed for ...
Retrieved 5 items
Total context chars: 4078
Types: ['text', 'text', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 5246
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1115

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1243
Raw output length: 5758
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is the treatment of choice for acalculous cholecystitis. It is safe and...'
Answer length: 512
Final answer: 'Laparoscopic cholecystectomy is the treatment of choice for acalculous cholecystitis. It is safe and...'

Processing question 9/30: What are the absolute contraindications to laparos...
Retrieved 5 items
Total context chars: 4636
Types: ['text', 'text', 'video', 'text', 'video']
System prompt length: 1032
Full prompt length: 5801
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1219

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1347
Raw output length: 6469
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'There are no absolute contraindications to laparoscopic cholecystectomy. However, certain conditions...'
Answer length: 668
Final answer: 'There are no absolute contraindications to laparoscopic cholecystectomy. However, certain conditions...'

Processing question 10/30: Tokyo Guidelines 2018: How should Grade I acute ch...
Retrieved 5 items
Total context chars: 5283
Types: ['text', 'text', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 6449
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1449

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1577
Raw output length: 7166
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Grade I acute cholecystitis is characterized by mild symptoms and is often managed conservatively. T...'
Answer length: 717
Final answer: 'Grade I acute cholecystitis is characterized by mild symptoms and is often managed conservatively. T...'

Processing question 11/30: How are high‑grade bile leaks managed after cholec...
Retrieved 5 items
Total context chars: 3141
Types: ['text', 'video', 'video', 'video', 'text']
System prompt length: 1032
Full prompt length: 4294
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 905

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1033
Raw output length: 4826
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'High-grade bile leaks are managed with endoscopic retrograde cholangiopancreatography (ERCP) with st...'
Answer length: 532
Final answer: 'High-grade bile leaks are managed with endoscopic retrograde cholangiopancreatography (ERCP) with st...'

Processing question 12/30: Is cholecystectomy indicated after gallstone pancr...
Retrieved 5 items
Total context chars: 3507
Types: ['text', 'video', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 4658
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1018

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1146
Raw output length: 5329
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Cholecystectomy is indicated after gallstone pancreatitis. The critical view of safety prevents bile...'
Answer length: 670
Final answer: 'Cholecystectomy is indicated after gallstone pancreatitis. The critical view of safety prevents bile...'

Processing question 13/30: What advantages does laparoscopic cholecystectomy ...
Retrieved 5 items
Total context chars: 4614
Types: ['text', 'video', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 5781
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1236

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1364
Raw output length: 6468
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy offers several advantages over open surgery, including smaller incision...'
Answer length: 687
Final answer: 'Laparoscopic cholecystectomy offers several advantages over open surgery, including smaller incision...'

Processing question 14/30: When should conversion to open cholecystectomy be ...
Retrieved 5 items
Total context chars: 6101
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7239
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1651

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1779
Raw output length: 7840
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Conversion to open cholecystectomy should be considered when there is concern about the security of ...'
Answer length: 601
Final answer: 'Conversion to open cholecystectomy should be considered when there is concern about the security of ...'

Processing question 15/30: Are asymptomatic gallstones an indication for chol...
Retrieved 5 items
Total context chars: 3414
Types: ['video', 'text', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 4569
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1010

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1138
Raw output length: 5198
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, asymptomatic gallstones are not an indication for cholecystectomy. In fact, the majority of pati...'
Answer length: 628
Final answer: 'No, asymptomatic gallstones are not an indication for cholecystectomy. In fact, the majority of pati...'

Processing question 16/30: How should common bile duct stones detected preope...
Retrieved 5 items
Total context chars: 3550
Types: ['video', 'text', 'video', 'video', 'text']
System prompt length: 1032
Full prompt length: 4713
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1024

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1152
Raw output length: 5326
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Common bile duct stones detected preoperatively should be managed with a preoperative ERCP. If ERCP ...'
Answer length: 612
Final answer: 'Common bile duct stones detected preoperatively should be managed with a preoperative ERCP. If ERCP ...'

Processing question 17/30: When can patients usually resume normal activities...
Retrieved 5 items
Total context chars: 3094
Types: ['video', 'video', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 4273
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 893

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1021
Raw output length: 4918
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'
Answer length: 645
Final answer: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'

Processing question 18/30: What do SAGES guidelines say about routinely achie...
Retrieved 5 items
Total context chars: 4822
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 5998
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1441

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1569
Raw output length: 6670
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'SAGES guidelines recommend routinely achieving the critical view of safety during laparoscopic chole...'
Answer length: 671
Final answer: 'SAGES guidelines recommend routinely achieving the critical view of safety during laparoscopic chole...'

Processing question 19/30: What are the most common intraoperative complicati...
Retrieved 5 items
Total context chars: 4539
Types: ['text', 'text', 'video', 'text', 'video']
System prompt length: 1032
Full prompt length: 5718
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1195

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1323
Raw output length: 6343
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The most common intraoperative complications of laparoscopic cholecystectomy are bile duct injury, b...'
Answer length: 625
Final answer: 'The most common intraoperative complications of laparoscopic cholecystectomy are bile duct injury, b...'

Processing question 20/30: Is laparoscopic cholecystectomy safe during pregna...
Retrieved 5 items
Total context chars: 2464
Types: ['video', 'video', 'video', 'video', 'text']
System prompt length: 1032
Full prompt length: 3611
Context items: 5 (1 text, 4 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 783

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 911
Raw output length: 4296
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is safe during pregnancy. The critical view of safety prevents bile duc...'
Answer length: 685
Final answer: 'Laparoscopic cholecystectomy is safe during pregnancy. The critical view of safety prevents bile duc...'

Processing question 21/30: What constitutes the critical view of safety in la...
Retrieved 5 items
Total context chars: 4391
Types: ['text', 'video', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 5561
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1252

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1380
Raw output length: 6191
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The critical view of safety requires clearing the hepatocystic triangle of fat and tissue, separatin...'
Answer length: 630
Final answer: 'The critical view of safety requires clearing the hepatocystic triangle of fat and tissue, separatin...'

Processing question 22/30: How are postoperative bile leaks diagnosed?...
Retrieved 5 items
Total context chars: 3782
Types: ['text', 'text', 'video', 'video', 'video']
System prompt length: 1032
Full prompt length: 4918
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1077

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1205
Raw output length: 5558
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Postoperative bile leaks are diagnosed by a combination of clinical presentation, laboratory tests, ...'
Answer length: 639
Final answer: 'Postoperative bile leaks are diagnosed by a combination of clinical presentation, laboratory tests, ...'

Processing question 23/30: When should intraoperative cholangiography be perf...
Retrieved 5 items
Total context chars: 3847
Types: ['video', 'video', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 4996
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1066

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1194
Raw output length: 5592
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Intraoperative cholangiography should be performed after division of the cystic duct to ensure that ...'
Answer length: 595
Final answer: 'Intraoperative cholangiography should be performed after division of the cystic duct to ensure that ...'

Processing question 24/30: How long is the typical hospital stay after uncomp...
Retrieved 5 items
Total context chars: 4105
Types: ['text', 'text', 'video', 'text', 'video']
System prompt length: 1032
Full prompt length: 5285
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1227

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1355
Raw output length: 5896
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'
Answer length: 611
Final answer: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'

Processing question 25/30: Are prophylactic antibiotics required for all lapa...
Retrieved 5 items
Total context chars: 6034
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7188
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1616

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1744
Raw output length: 7812
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The use of pro...'
Answer length: 624
Final answer: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The use of pro...'

Processing question 26/30: Tokyo Guidelines 2018: Management strategy for Gra...
Retrieved 5 items
Total context chars: 4260
Types: ['text', 'text', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 5429
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1334

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1462
Raw output length: 6157
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend a conservative treatment strategy for patients with Grade II acu...'
Answer length: 727
Final answer: 'The Tokyo Guidelines 2018 recommend a conservative treatment strategy for patients with Grade II acu...'

Processing question 27/30: What is fluorescent indocyanine‑green cholangiogra...
Retrieved 5 items
Total context chars: 2763
Types: ['text', 'video', 'video', 'video', 'video']
System prompt length: 1032
Full prompt length: 3930
Context items: 5 (1 text, 4 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 845

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 973
Raw output length: 4556
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Fluorescent indocyanine‑green cholangiography is a novel technique that can be used to identify bile...'
Answer length: 626
Final answer: 'Fluorescent indocyanine‑green cholangiography is a novel technique that can be used to identify bile...'

Processing question 28/30: What is SAGES guidance on intraoperative cholangio...
Retrieved 5 items
Total context chars: 3811
Types: ['text', 'video', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 4967
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1106

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1234
Raw output length: 5528
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'SAGES recommends routine IOC during laparoscopic cholecystectomy to prevent bile duct injury. The pa...'
Answer length: 561
Final answer: 'SAGES recommends routine IOC during laparoscopic cholecystectomy to prevent bile duct injury. The pa...'

Processing question 29/30: What is the incidence of bile duct injury in lapar...
Retrieved 5 items
Total context chars: 3577
Types: ['text', 'text', 'video', 'video', 'video']
System prompt length: 1032
Full prompt length: 4744
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 995

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1123
Raw output length: 5418
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Bile duct injury (BDI) is the most serious complication of laparoscopic cholecystectomy and has been...'
Answer length: 674
Final answer: 'Bile duct injury (BDI) is the most serious complication of laparoscopic cholecystectomy and has been...'

Processing question 30/30: How are the cystic duct and artery managed once th...
Retrieved 5 items
Total context chars: 1802
Types: ['video', 'video', 'video', 'video', 'video']
System prompt length: 1032
Full prompt length: 2959
Context items: 5 (0 text, 5 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 648
Generated token length: 776
Raw output length: 3552
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Once the critical view of safety is achieved, the cystic duct and cystic artery are divided using a ...'
Answer length: 592
Final answer: 'Once the critical view of safety is achieved, the cystic duct and cystic artery are divided using a ...'
Running combo: fine_retr-none_rerank-fine_gen

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Loaded 77 video segments for transcript-based retrieval

Processing question 1/30: How should the patient be positioned for laparosco...
Retrieved 5 items
Total context chars: 5661
Types: ['text', 'video', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6824
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1523

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1651
Raw output length: 7463
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'
Answer length: 638
Final answer: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'

Processing question 2/30: What are the common indications for laparoscopic c...
Retrieved 5 items
Total context chars: 4833
Types: ['text', 'text', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 5991
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1246

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1374
Raw output length: 6579
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The common indications for laparoscopic cholecystectomy include symptomatic gallstones, gallbladder ...'
Answer length: 588
Final answer: 'The common indications for laparoscopic cholecystectomy include symptomatic gallstones, gallbladder ...'

Processing question 3/30: Tokyo Guidelines 2018: Recommended management for ...
Retrieved 5 items
Total context chars: 4958
Types: ['text', 'text', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 6131
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1468

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1596
Raw output length: 6817
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should undergo ...'
Answer length: 686
Final answer: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should undergo ...'

Processing question 4/30: How many laparoscopic ports are typically used, an...
Retrieved 5 items
Total context chars: 1722
Types: ['video', 'video', 'video', 'video', 'video']
System prompt length: 1032
Full prompt length: 2885
Context items: 5 (0 text, 5 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 634

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 762
Raw output length: 3489
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Four ports are typically used. The camera port is 10mm and is placed in the supra umbilical region. ...'
Answer length: 604
Final answer: 'Four ports are typically used. The camera port is 10mm and is placed in the supra umbilical region. ...'

Processing question 5/30: How does surgeon experience influence outcomes in ...
Retrieved 5 items
Total context chars: 5206
Types: ['text', 'text', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 6378
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1465

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1593
Raw output length: 7029
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. Studies have sh...'
Answer length: 651
Final answer: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. Studies have sh...'

Processing question 6/30: What is the standard approach if gallbladder carci...
Retrieved 5 items
Total context chars: 4171
Types: ['text', 'video', 'video', 'text', 'video']
System prompt length: 1032
Full prompt length: 5347
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1144

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1272
Raw output length: 5981
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'If gallbladdar carcinoma is suspected during surgery, the standard approach is to convert to an open...'
Answer length: 633
Final answer: 'If gallbladdar carcinoma is suspected during surgery, the standard approach is to convert to an open...'

Processing question 7/30: What are relative contraindications to laparoscopi...
Retrieved 5 items
Total context chars: 5540
Types: ['text', 'text', 'video', 'text', 'text']
System prompt length: 1032
Full prompt length: 6701
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1424

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1552
Raw output length: 7281
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Relative contraindications to laparoscopic cholecystectomy include a history of Roux Y gastric bypas...'
Answer length: 580
Final answer: 'Relative contraindications to laparoscopic cholecystectomy include a history of Roux Y gastric bypas...'

Processing question 8/30: Can laparoscopic cholecystectomy be performed for ...
Retrieved 5 items
Total context chars: 4078
Types: ['text', 'text', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 5246
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1115

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1243
Raw output length: 5758
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is the treatment of choice for acalculous cholecystitis. It is safe and...'
Answer length: 512
Final answer: 'Laparoscopic cholecystectomy is the treatment of choice for acalculous cholecystitis. It is safe and...'

Processing question 9/30: What are the absolute contraindications to laparos...
Retrieved 5 items
Total context chars: 4636
Types: ['text', 'text', 'video', 'text', 'video']
System prompt length: 1032
Full prompt length: 5801
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1219

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1347
Raw output length: 6469
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'There are no absolute contraindications to laparoscopic cholecystectomy. However, certain conditions...'
Answer length: 668
Final answer: 'There are no absolute contraindications to laparoscopic cholecystectomy. However, certain conditions...'

Processing question 10/30: Tokyo Guidelines 2018: How should Grade I acute ch...
Retrieved 5 items
Total context chars: 5283
Types: ['text', 'text', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 6449
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1449

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1577
Raw output length: 7166
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Grade I acute cholecystitis is characterized by mild symptoms and is often managed conservatively. T...'
Answer length: 717
Final answer: 'Grade I acute cholecystitis is characterized by mild symptoms and is often managed conservatively. T...'

Processing question 11/30: How are high‑grade bile leaks managed after cholec...
Retrieved 5 items
Total context chars: 3141
Types: ['text', 'video', 'video', 'video', 'text']
System prompt length: 1032
Full prompt length: 4294
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 905

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1033
Raw output length: 4826
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'High-grade bile leaks are managed with endoscopic retrograde cholangiopancreatography (ERCP) with st...'
Answer length: 532
Final answer: 'High-grade bile leaks are managed with endoscopic retrograde cholangiopancreatography (ERCP) with st...'

Processing question 12/30: Is cholecystectomy indicated after gallstone pancr...
Retrieved 5 items
Total context chars: 3507
Types: ['text', 'video', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 4658
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1018

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1146
Raw output length: 5329
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Cholecystectomy is indicated after gallstone pancreatitis. The critical view of safety prevents bile...'
Answer length: 670
Final answer: 'Cholecystectomy is indicated after gallstone pancreatitis. The critical view of safety prevents bile...'

Processing question 13/30: What advantages does laparoscopic cholecystectomy ...
Retrieved 5 items
Total context chars: 4614
Types: ['text', 'video', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 5781
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1236

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1364
Raw output length: 6468
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy offers several advantages over open surgery, including smaller incision...'
Answer length: 687
Final answer: 'Laparoscopic cholecystectomy offers several advantages over open surgery, including smaller incision...'

Processing question 14/30: When should conversion to open cholecystectomy be ...
Retrieved 5 items
Total context chars: 6101
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7239
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1651

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1779
Raw output length: 7840
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Conversion to open cholecystectomy should be considered when there is concern about the security of ...'
Answer length: 601
Final answer: 'Conversion to open cholecystectomy should be considered when there is concern about the security of ...'

Processing question 15/30: Are asymptomatic gallstones an indication for chol...
Retrieved 5 items
Total context chars: 3414
Types: ['video', 'text', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 4569
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1010

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1138
Raw output length: 5198
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, asymptomatic gallstones are not an indication for cholecystectomy. In fact, the majority of pati...'
Answer length: 628
Final answer: 'No, asymptomatic gallstones are not an indication for cholecystectomy. In fact, the majority of pati...'

Processing question 16/30: How should common bile duct stones detected preope...
Retrieved 5 items
Total context chars: 3550
Types: ['video', 'text', 'video', 'video', 'text']
System prompt length: 1032
Full prompt length: 4713
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1024

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1152
Raw output length: 5326
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Common bile duct stones detected preoperatively should be managed with a preoperative ERCP. If ERCP ...'
Answer length: 612
Final answer: 'Common bile duct stones detected preoperatively should be managed with a preoperative ERCP. If ERCP ...'

Processing question 17/30: When can patients usually resume normal activities...
Retrieved 5 items
Total context chars: 3094
Types: ['video', 'video', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 4273
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 893

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1021
Raw output length: 4918
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'
Answer length: 645
Final answer: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'

Processing question 18/30: What do SAGES guidelines say about routinely achie...
Retrieved 5 items
Total context chars: 4822
Types: ['text', 'text', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 5998
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1441

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1569
Raw output length: 6670
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'SAGES guidelines recommend routinely achieving the critical view of safety during laparoscopic chole...'
Answer length: 671
Final answer: 'SAGES guidelines recommend routinely achieving the critical view of safety during laparoscopic chole...'

Processing question 19/30: What are the most common intraoperative complicati...
Retrieved 5 items
Total context chars: 4539
Types: ['text', 'text', 'video', 'text', 'video']
System prompt length: 1032
Full prompt length: 5718
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1195

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1323
Raw output length: 6343
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The most common intraoperative complications of laparoscopic cholecystectomy are bile duct injury, b...'
Answer length: 625
Final answer: 'The most common intraoperative complications of laparoscopic cholecystectomy are bile duct injury, b...'

Processing question 20/30: Is laparoscopic cholecystectomy safe during pregna...
Retrieved 5 items
Total context chars: 2464
Types: ['video', 'video', 'video', 'video', 'text']
System prompt length: 1032
Full prompt length: 3611
Context items: 5 (1 text, 4 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 783

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 911
Raw output length: 4296
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is safe during pregnancy. The critical view of safety prevents bile duc...'
Answer length: 685
Final answer: 'Laparoscopic cholecystectomy is safe during pregnancy. The critical view of safety prevents bile duc...'

Processing question 21/30: What constitutes the critical view of safety in la...
Retrieved 5 items
Total context chars: 4391
Types: ['text', 'video', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 5561
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1252

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1380
Raw output length: 6191
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The critical view of safety requires clearing the hepatocystic triangle of fat and tissue, separatin...'
Answer length: 630
Final answer: 'The critical view of safety requires clearing the hepatocystic triangle of fat and tissue, separatin...'

Processing question 22/30: How are postoperative bile leaks diagnosed?...
Retrieved 5 items
Total context chars: 3782
Types: ['text', 'text', 'video', 'video', 'video']
System prompt length: 1032
Full prompt length: 4918
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1077

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1205
Raw output length: 5558
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Postoperative bile leaks are diagnosed by a combination of clinical presentation, laboratory tests, ...'
Answer length: 639
Final answer: 'Postoperative bile leaks are diagnosed by a combination of clinical presentation, laboratory tests, ...'

Processing question 23/30: When should intraoperative cholangiography be perf...
Retrieved 5 items
Total context chars: 3847
Types: ['video', 'video', 'text', 'text', 'video']
System prompt length: 1032
Full prompt length: 4996
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1066

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1194
Raw output length: 5592
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Intraoperative cholangiography should be performed after division of the cystic duct to ensure that ...'
Answer length: 595
Final answer: 'Intraoperative cholangiography should be performed after division of the cystic duct to ensure that ...'

Processing question 24/30: How long is the typical hospital stay after uncomp...
Retrieved 5 items
Total context chars: 4105
Types: ['text', 'text', 'video', 'text', 'video']
System prompt length: 1032
Full prompt length: 5285
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1227

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1355
Raw output length: 5896
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'
Answer length: 611
Final answer: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'

Processing question 25/30: Are prophylactic antibiotics required for all lapa...
Retrieved 5 items
Total context chars: 6034
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7188
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1616

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1744
Raw output length: 7812
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The use of pro...'
Answer length: 624
Final answer: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The use of pro...'

Processing question 26/30: Tokyo Guidelines 2018: Management strategy for Gra...
Retrieved 5 items
Total context chars: 4260
Types: ['text', 'text', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 5429
Context items: 5 (3 text, 2 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1334

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1462
Raw output length: 6157
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend a conservative treatment strategy for patients with Grade II acu...'
Answer length: 727
Final answer: 'The Tokyo Guidelines 2018 recommend a conservative treatment strategy for patients with Grade II acu...'

Processing question 27/30: What is fluorescent indocyanine‑green cholangiogra...
Retrieved 5 items
Total context chars: 2763
Types: ['text', 'video', 'video', 'video', 'video']
System prompt length: 1032
Full prompt length: 3930
Context items: 5 (1 text, 4 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 845

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 973
Raw output length: 4556
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Fluorescent indocyanine‑green cholangiography is a novel technique that can be used to identify bile...'
Answer length: 626
Final answer: 'Fluorescent indocyanine‑green cholangiography is a novel technique that can be used to identify bile...'

Processing question 28/30: What is SAGES guidance on intraoperative cholangio...
Retrieved 5 items
Total context chars: 3811
Types: ['text', 'video', 'text', 'video', 'video']
System prompt length: 1032
Full prompt length: 4967
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1106

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1234
Raw output length: 5528
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'SAGES recommends routine IOC during laparoscopic cholecystectomy to prevent bile duct injury. The pa...'
Answer length: 561
Final answer: 'SAGES recommends routine IOC during laparoscopic cholecystectomy to prevent bile duct injury. The pa...'

Processing question 29/30: What is the incidence of bile duct injury in lapar...
Retrieved 5 items
Total context chars: 3577
Types: ['text', 'text', 'video', 'video', 'video']
System prompt length: 1032
Full prompt length: 4744
Context items: 5 (2 text, 3 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 995

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1123
Raw output length: 5418
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Bile duct injury (BDI) is the most serious complication of laparoscopic cholecystectomy and has been...'
Answer length: 674
Final answer: 'Bile duct injury (BDI) is the most serious complication of laparoscopic cholecystectomy and has been...'

Processing question 30/30: How are the cystic duct and artery managed once th...
Retrieved 5 items
Total context chars: 1802
Types: ['video', 'video', 'video', 'video', 'video']
System prompt length: 1032
Full prompt length: 2959
Context items: 5 (0 text, 5 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 648
Generated token length: 776
Raw output length: 3552
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Once the critical view of safety is achieved, the cystic duct and cystic artery are divided using a ...'
Answer length: 592
Final answer: 'Once the critical view of safety is achieved, the cystic duct and cystic artery are divided using a ...'
Running combo: fine_retr-cross_rerank-base_gen
Loaded 77 video segments for transcript-based retrieval

Processing question 1/30: How should the patient be positioned for laparosco...

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Retrieved 5 items
Total context chars: 6268
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7415
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1643

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1771
Raw output length: 8071
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'
Answer length: 656
Final answer: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'

Processing question 2/30: What are the common indications for laparoscopic c...
Retrieved 5 items
Total context chars: 5551
Types: ['text', 'text', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 6709
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1444

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1572
Raw output length: 7316
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The common indications for laparoscopic cholecystectomy include symptomatic gallstones, gallbladder ...'
Answer length: 607
Final answer: 'The common indications for laparoscopic cholecystectomy include symptomatic gallstones, gallbladder ...'

Processing question 3/30: Tokyo Guidelines 2018: Recommended management for ...
Retrieved 5 items
Total context chars: 6796
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7953
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1730

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1858
Raw output length: 8642
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should undergo ...'
Answer length: 688
Final answer: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should undergo ...'

Processing question 4/30: How many laparoscopic ports are typically used, an...
Retrieved 5 items
Total context chars: 2646
Types: ['video', 'text', 'video', 'video', 'video']
System prompt length: 1032
Full prompt length: 3823
Context items: 5 (1 text, 4 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 890

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1018
Raw output length: 4451
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Four ports are typically used. The camera port is placed in the supra umbilical region. The ports ac...'
Answer length: 627
Final answer: 'Four ports are typically used. The camera port is placed in the supra umbilical region. The ports ac...'

Processing question 5/30: How does surgeon experience influence outcomes in ...
Retrieved 5 items
Total context chars: 5361
Types: ['text', 'video', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6533
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1437

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1565
Raw output length: 7246
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. Studies have sh...'
Answer length: 713
Final answer: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. Studies have sh...'

Processing question 6/30: What is the standard approach if gallbladder carci...
Retrieved 5 items
Total context chars: 6851
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 8011
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1709

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1837
Raw output length: 8646
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'If gallbladders carcinoma is suspected during surgery, the standard approach is to convert to an ope...'
Answer length: 634
Final answer: 'If gallbladders carcinoma is suspected during surgery, the standard approach is to convert to an ope...'

Processing question 7/30: What are relative contraindications to laparoscopi...
Retrieved 5 items
Total context chars: 6438
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7583
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1635

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1763
Raw output length: 8272
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Relative contraindications to laparoscopic cholecystectomy include severe obesity, previous upper ab...'
Answer length: 689
Final answer: 'Relative contraindications to laparoscopic cholecystectomy include severe obesity, previous upper ab...'

Processing question 8/30: Can laparoscopic cholecystectomy be performed for ...
Retrieved 5 items
Total context chars: 6463
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7615
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1639

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1767
Raw output length: 8197
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is considered safe and effective for the treatment of acalculous cholec...'
Answer length: 582
Final answer: 'Laparoscopic cholecystectomy is considered safe and effective for the treatment of acalculous cholec...'

Processing question 9/30: What are the absolute contraindications to laparos...
Retrieved 5 items
Total context chars: 6438
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7587
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1636

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1764
Raw output length: 8226
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'There are no absolute contraindications to laparoscopic cholecystectomy. However, certain conditions...'
Answer length: 639
Final answer: 'There are no absolute contraindications to laparoscopic cholecystectomy. However, certain conditions...'

Processing question 10/30: Tokyo Guidelines 2018: How should Grade I acute ch...
Retrieved 5 items
Total context chars: 6796
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7946
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1731

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1859
Raw output length: 8600
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Grade I acute cholecystitis is characterized by mild symptoms and no signs of pericholecystic fluid....'
Answer length: 653
Final answer: 'Grade I acute cholecystitis is characterized by mild symptoms and no signs of pericholecystic fluid....'

Processing question 11/30: How are high‑grade bile leaks managed after cholec...
Retrieved 5 items
Total context chars: 6725
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7862
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1705

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1833
Raw output length: 8399
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'High-grade bile leaks are managed with endoscopic retrograde cholangiography and stenting (ERCP) or ...'
Answer length: 536
Final answer: 'High-grade bile leaks are managed with endoscopic retrograde cholangiography and stenting (ERCP) or ...'

Processing question 12/30: Is cholecystectomy indicated after gallstone pancr...
Retrieved 5 items
Total context chars: 6457
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7592
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1756

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1884
Raw output length: 8147
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Cholecystectomy is indicated after gallstone pancreatitis. The most common complication of laparosco...'
Answer length: 555
Final answer: 'Cholecystectomy is indicated after gallstone pancreatitis. The most common complication of laparosco...'

Processing question 13/30: What advantages does laparoscopic cholecystectomy ...
Retrieved 5 items
Total context chars: 5531
Types: ['video', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6698
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1428

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1556
Raw output length: 7308
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy offers several advantages over open surgery, including reduced cost, sh...'
Answer length: 610
Final answer: 'Laparoscopic cholecystectomy offers several advantages over open surgery, including reduced cost, sh...'

Processing question 14/30: When should conversion to open cholecystectomy be ...
Retrieved 5 items
Total context chars: 5682
Types: ['text', 'text', 'video', 'text', 'text']
System prompt length: 1032
Full prompt length: 6836
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1428

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1556
Raw output length: 7476
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Conversion to open cholecystectomy should be considered when the laparoscopic approach is not feasib...'
Answer length: 640
Final answer: 'Conversion to open cholecystectomy should be considered when the laparoscopic approach is not feasib...'

Processing question 15/30: Are asymptomatic gallstones an indication for chol...
Retrieved 5 items
Total context chars: 6490
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7629
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1751

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1879
Raw output length: 8310
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, asymptomatic gallstones are not an indication for cholecystectomy. In fact, the American Gastroe...'
Answer length: 680
Final answer: 'No, asymptomatic gallstones are not an indication for cholecystectomy. In fact, the American Gastroe...'

Processing question 16/30: How should common bile duct stones detected preope...
Retrieved 5 items
Total context chars: 6809
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7956
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1725

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1853
Raw output length: 8641
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Common bile duct stones detected preoperatively should be managed with preoperative ERCP. Common bil...'
Answer length: 684
Final answer: 'Common bile duct stones detected preoperatively should be managed with preoperative ERCP. Common bil...'

Processing question 17/30: When can patients usually resume normal activities...
Retrieved 5 items
Total context chars: 6142
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7305
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1641

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1769
Raw output length: 7960
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'
Answer length: 655
Final answer: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'

Processing question 18/30: What do SAGES guidelines say about routinely achie...
Retrieved 5 items
Total context chars: 5956
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7116
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1594

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1722
Raw output length: 7782
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'SAGES guidelines recommend routinely achieving the critical view of safety during laparoscopic chole...'
Answer length: 665
Final answer: 'SAGES guidelines recommend routinely achieving the critical view of safety during laparoscopic chole...'

Processing question 19/30: What are the most common intraoperative complicati...
Retrieved 5 items
Total context chars: 5444
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6607
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1524

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1652
Raw output length: 7229
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The most common intraoperative complications of laparoscopic cholecystectomy are bile duct injury, b...'
Answer length: 622
Final answer: 'The most common intraoperative complications of laparoscopic cholecystectomy are bile duct injury, b...'

Processing question 20/30: Is laparoscopic cholecystectomy safe during pregna...
Retrieved 5 items
Total context chars: 6463
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7594
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1631

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1759
Raw output length: 8324
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is safe during pregnancy. The procedure is considered safe for pregnant...'
Answer length: 730
Final answer: 'Laparoscopic cholecystectomy is safe during pregnancy. The procedure is considered safe for pregnant...'

Processing question 21/30: What constitutes the critical view of safety in la...
Retrieved 5 items
Total context chars: 5520
Types: ['text', 'text', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 6690
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1426

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1554
Raw output length: 7285
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The critical view of safety requires three criteria to be met: (I) the hepatocystic triangle (define...'
Answer length: 595
Final answer: 'The critical view of safety requires three criteria to be met: (I) the hepatocystic triangle (define...'

Processing question 22/30: How are postoperative bile leaks diagnosed?...
Retrieved 5 items
Total context chars: 6625
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7745
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1695

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1823
Raw output length: 8343
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Postoperative bile leaks are diagnosed by a combination of clinical presentation, laboratory finding...'
Answer length: 598
Final answer: 'Postoperative bile leaks are diagnosed by a combination of clinical presentation, laboratory finding...'

Processing question 23/30: When should intraoperative cholangiography be perf...
Retrieved 5 items
Total context chars: 6390
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7523
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1717

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1845
Raw output length: 8110
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Intraoperative cholangiography should be performed in cases of suspicion of CBD stones (history of a...'
Answer length: 586
Final answer: 'Intraoperative cholangiography should be performed in cases of suspicion of CBD stones (history of a...'

Processing question 24/30: How long is the typical hospital stay after uncomp...
Retrieved 5 items
Total context chars: 6142
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7306
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1643

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1771
Raw output length: 7930
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'
Answer length: 624
Final answer: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'

Processing question 25/30: Are prophylactic antibiotics required for all lapa...
Retrieved 5 items
Total context chars: 6463
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7617
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1637

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1765
Raw output length: 8254
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The use of pro...'
Answer length: 637
Final answer: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The use of pro...'

Processing question 26/30: Tokyo Guidelines 2018: Management strategy for Gra...
Retrieved 5 items
Total context chars: 6796
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7949
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1730

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1858
Raw output length: 8666
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend a conservative treatment strategy for patients with Grade II acu...'
Answer length: 716
Final answer: 'The Tokyo Guidelines 2018 recommend a conservative treatment strategy for patients with Grade II acu...'

Processing question 27/30: What is fluorescent indocyanine‑green cholangiogra...
Retrieved 5 items
Total context chars: 6575
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7726
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1735

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1863
Raw output length: 8254
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Fluorescent indocyanine‑green cholangiography (ICG-FC) is a novel, real-time, intraoperative imaging...'
Answer length: 528
Final answer: 'Fluorescent indocyanine‑green cholangiography (ICG-FC) is a novel, real-time, intraoperative imaging...'

Processing question 28/30: What is SAGES guidance on intraoperative cholangio...
Retrieved 5 items
Total context chars: 6556
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7696
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1725

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1853
Raw output length: 8318
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'SAGES recommends routine IOC in all patients undergoing laparoscopic cholecystectomy. IOC is perform...'
Answer length: 621
Final answer: 'SAGES recommends routine IOC in all patients undergoing laparoscopic cholecystectomy. IOC is perform...'

Processing question 29/30: What is the incidence of bile duct injury in lapar...
Retrieved 5 items
Total context chars: 6142
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7293
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1642

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1770
Raw output length: 7870
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Bile duct injury (BDI) is the most serious complication of laparoscopic cholecystectomy and occurs i...'
Answer length: 577
Final answer: 'Bile duct injury (BDI) is the most serious complication of laparoscopic cholecystectomy and occurs i...'

Processing question 30/30: How are the cystic duct and artery managed once th...
Retrieved 5 items
Total context chars: 5876
Types: ['text', 'video', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7047
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1536
Generated token length: 1664
Raw output length: 7596
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Once the critical view of safety is established, the cystic artery is clipped and divided. The cysti...'
Answer length: 548
Final answer: 'Once the critical view of safety is established, the cystic artery is clipped and divided. The cysti...'
Running combo: fine_retr-cross_rerank-fine_gen
Loaded 77 video segments for transcript-based retrieval

Processing question 1/30: How should the patient be positioned for laparosco...
Retrieved 5 items
Total context chars: 6268
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7415
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Input token length: 1643

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1771
Raw output length: 8071
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'
Answer length: 656
Final answer: 'The patient is placed in supine position with the left arm tucked to facilitate intraoperative chola...'

Processing question 2/30: What are the common indications for laparoscopic c...
Retrieved 5 items
Total context chars: 5551
Types: ['text', 'text', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 6709
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1444

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1572
Raw output length: 7316
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The common indications for laparoscopic cholecystectomy include symptomatic gallstones, gallbladder ...'
Answer length: 607
Final answer: 'The common indications for laparoscopic cholecystectomy include symptomatic gallstones, gallbladder ...'

Processing question 3/30: Tokyo Guidelines 2018: Recommended management for ...
Retrieved 5 items
Total context chars: 6796
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7953
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1730

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1858
Raw output length: 8642
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should undergo ...'
Answer length: 688
Final answer: 'The Tokyo Guidelines 2018 recommend that patients with Grade III acute cholecystitis should undergo ...'

Processing question 4/30: How many laparoscopic ports are typically used, an...
Retrieved 5 items
Total context chars: 2646
Types: ['video', 'text', 'video', 'video', 'video']
System prompt length: 1032
Full prompt length: 3823
Context items: 5 (1 text, 4 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 890

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1018
Raw output length: 4451
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Four ports are typically used. The camera port is placed in the supra umbilical region. The ports ac...'
Answer length: 627
Final answer: 'Four ports are typically used. The camera port is placed in the supra umbilical region. The ports ac...'

Processing question 5/30: How does surgeon experience influence outcomes in ...
Retrieved 5 items
Total context chars: 5361
Types: ['text', 'video', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6533
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1437

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1565
Raw output length: 7246
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. Studies have sh...'
Answer length: 713
Final answer: 'Surgeon experience is a significant factor in laparoscopic cholecystectomy outcomes. Studies have sh...'

Processing question 6/30: What is the standard approach if gallbladder carci...
Retrieved 5 items
Total context chars: 6851
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 8011
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1709

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1837
Raw output length: 8646
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'If gallbladders carcinoma is suspected during surgery, the standard approach is to convert to an ope...'
Answer length: 634
Final answer: 'If gallbladders carcinoma is suspected during surgery, the standard approach is to convert to an ope...'

Processing question 7/30: What are relative contraindications to laparoscopi...
Retrieved 5 items
Total context chars: 6438
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7583
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1635

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1763
Raw output length: 8272
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Relative contraindications to laparoscopic cholecystectomy include severe obesity, previous upper ab...'
Answer length: 689
Final answer: 'Relative contraindications to laparoscopic cholecystectomy include severe obesity, previous upper ab...'

Processing question 8/30: Can laparoscopic cholecystectomy be performed for ...
Retrieved 5 items
Total context chars: 6463
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7615
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1639

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1767
Raw output length: 8197
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is considered safe and effective for the treatment of acalculous cholec...'
Answer length: 582
Final answer: 'Laparoscopic cholecystectomy is considered safe and effective for the treatment of acalculous cholec...'

Processing question 9/30: What are the absolute contraindications to laparos...
Retrieved 5 items
Total context chars: 6438
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7587
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1636

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1764
Raw output length: 8226
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'There are no absolute contraindications to laparoscopic cholecystectomy. However, certain conditions...'
Answer length: 639
Final answer: 'There are no absolute contraindications to laparoscopic cholecystectomy. However, certain conditions...'

Processing question 10/30: Tokyo Guidelines 2018: How should Grade I acute ch...
Retrieved 5 items
Total context chars: 6796
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7946
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1731

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1859
Raw output length: 8600
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Grade I acute cholecystitis is characterized by mild symptoms and no signs of pericholecystic fluid....'
Answer length: 653
Final answer: 'Grade I acute cholecystitis is characterized by mild symptoms and no signs of pericholecystic fluid....'

Processing question 11/30: How are high‑grade bile leaks managed after cholec...
Retrieved 5 items
Total context chars: 6725
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7862
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1705

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1833
Raw output length: 8399
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'High-grade bile leaks are managed with endoscopic retrograde cholangiography and stenting (ERCP) or ...'
Answer length: 536
Final answer: 'High-grade bile leaks are managed with endoscopic retrograde cholangiography and stenting (ERCP) or ...'

Processing question 12/30: Is cholecystectomy indicated after gallstone pancr...
Retrieved 5 items
Total context chars: 6457
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7592
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1756

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1884
Raw output length: 8147
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Cholecystectomy is indicated after gallstone pancreatitis. The most common complication of laparosco...'
Answer length: 555
Final answer: 'Cholecystectomy is indicated after gallstone pancreatitis. The most common complication of laparosco...'

Processing question 13/30: What advantages does laparoscopic cholecystectomy ...
Retrieved 5 items
Total context chars: 5531
Types: ['video', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6698
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1428

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1556
Raw output length: 7308
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy offers several advantages over open surgery, including reduced cost, sh...'
Answer length: 610
Final answer: 'Laparoscopic cholecystectomy offers several advantages over open surgery, including reduced cost, sh...'

Processing question 14/30: When should conversion to open cholecystectomy be ...
Retrieved 5 items
Total context chars: 5682
Types: ['text', 'text', 'video', 'text', 'text']
System prompt length: 1032
Full prompt length: 6836
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1428

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1556
Raw output length: 7476
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Conversion to open cholecystectomy should be considered when the laparoscopic approach is not feasib...'
Answer length: 640
Final answer: 'Conversion to open cholecystectomy should be considered when the laparoscopic approach is not feasib...'

Processing question 15/30: Are asymptomatic gallstones an indication for chol...
Retrieved 5 items
Total context chars: 6490
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7629
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1751

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1879
Raw output length: 8310
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, asymptomatic gallstones are not an indication for cholecystectomy. In fact, the American Gastroe...'
Answer length: 680
Final answer: 'No, asymptomatic gallstones are not an indication for cholecystectomy. In fact, the American Gastroe...'

Processing question 16/30: How should common bile duct stones detected preope...
Retrieved 5 items
Total context chars: 6809
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7956
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1725

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1853
Raw output length: 8641
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Common bile duct stones detected preoperatively should be managed with preoperative ERCP. Common bil...'
Answer length: 684
Final answer: 'Common bile duct stones detected preoperatively should be managed with preoperative ERCP. Common bil...'

Processing question 17/30: When can patients usually resume normal activities...
Retrieved 5 items
Total context chars: 6142
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7305
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1641

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1769
Raw output length: 7960
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'
Answer length: 655
Final answer: 'Patients can usually resume normal activities within 1-2 weeks after laparoscopic cholecystectomy. H...'

Processing question 18/30: What do SAGES guidelines say about routinely achie...
Retrieved 5 items
Total context chars: 5956
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7116
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1594

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1722
Raw output length: 7782
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'SAGES guidelines recommend routinely achieving the critical view of safety during laparoscopic chole...'
Answer length: 665
Final answer: 'SAGES guidelines recommend routinely achieving the critical view of safety during laparoscopic chole...'

Processing question 19/30: What are the most common intraoperative complicati...
Retrieved 5 items
Total context chars: 5444
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 6607
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1524

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1652
Raw output length: 7229
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The most common intraoperative complications of laparoscopic cholecystectomy are bile duct injury, b...'
Answer length: 622
Final answer: 'The most common intraoperative complications of laparoscopic cholecystectomy are bile duct injury, b...'

Processing question 20/30: Is laparoscopic cholecystectomy safe during pregna...
Retrieved 5 items
Total context chars: 6463
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7594
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1631

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1759
Raw output length: 8324
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Laparoscopic cholecystectomy is safe during pregnancy. The procedure is considered safe for pregnant...'
Answer length: 730
Final answer: 'Laparoscopic cholecystectomy is safe during pregnancy. The procedure is considered safe for pregnant...'

Processing question 21/30: What constitutes the critical view of safety in la...
Retrieved 5 items
Total context chars: 5520
Types: ['text', 'text', 'text', 'video', 'text']
System prompt length: 1032
Full prompt length: 6690
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1426

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1554
Raw output length: 7285
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The critical view of safety requires three criteria to be met: (I) the hepatocystic triangle (define...'
Answer length: 595
Final answer: 'The critical view of safety requires three criteria to be met: (I) the hepatocystic triangle (define...'

Processing question 22/30: How are postoperative bile leaks diagnosed?...
Retrieved 5 items
Total context chars: 6625
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7745
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1695

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1823
Raw output length: 8343
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Postoperative bile leaks are diagnosed by a combination of clinical presentation, laboratory finding...'
Answer length: 598
Final answer: 'Postoperative bile leaks are diagnosed by a combination of clinical presentation, laboratory finding...'

Processing question 23/30: When should intraoperative cholangiography be perf...
Retrieved 5 items
Total context chars: 6390
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7523
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1717

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1845
Raw output length: 8110
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Intraoperative cholangiography should be performed in cases of suspicion of CBD stones (history of a...'
Answer length: 586
Final answer: 'Intraoperative cholangiography should be performed in cases of suspicion of CBD stones (history of a...'

Processing question 24/30: How long is the typical hospital stay after uncomp...
Retrieved 5 items
Total context chars: 6142
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7306
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1643

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1771
Raw output length: 7930
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'
Answer length: 624
Final answer: 'The typical hospital stay after uncomplicated laparoscopic cholecystectomy is 1 day. The patient is ...'

Processing question 25/30: Are prophylactic antibiotics required for all lapa...
Retrieved 5 items
Total context chars: 6463
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7617
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1637

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1765
Raw output length: 8254
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The use of pro...'
Answer length: 637
Final answer: 'No, prophylactic antibiotics are not required for all laparoscopic cholecystectomies. The use of pro...'

Processing question 26/30: Tokyo Guidelines 2018: Management strategy for Gra...
Retrieved 5 items
Total context chars: 6796
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7949
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1730

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1858
Raw output length: 8666
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'The Tokyo Guidelines 2018 recommend a conservative treatment strategy for patients with Grade II acu...'
Answer length: 716
Final answer: 'The Tokyo Guidelines 2018 recommend a conservative treatment strategy for patients with Grade II acu...'

Processing question 27/30: What is fluorescent indocyanine‑green cholangiogra...
Retrieved 5 items
Total context chars: 6575
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7726
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1735

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1863
Raw output length: 8254
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Fluorescent indocyanine‑green cholangiography (ICG-FC) is a novel, real-time, intraoperative imaging...'
Answer length: 528
Final answer: 'Fluorescent indocyanine‑green cholangiography (ICG-FC) is a novel, real-time, intraoperative imaging...'

Processing question 28/30: What is SAGES guidance on intraoperative cholangio...
Retrieved 5 items
Total context chars: 6556
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7696
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1725

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1853
Raw output length: 8318
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'SAGES recommends routine IOC in all patients undergoing laparoscopic cholecystectomy. IOC is perform...'
Answer length: 621
Final answer: 'SAGES recommends routine IOC in all patients undergoing laparoscopic cholecystectomy. IOC is perform...'

Processing question 29/30: What is the incidence of bile duct injury in lapar...
Retrieved 5 items
Total context chars: 6142
Types: ['text', 'text', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7293
Context items: 5 (5 text, 0 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1642

The following generation flags are not valid and may be ignored: ['temperature', 'top_p']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Generated token length: 1770
Raw output length: 7870
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Bile duct injury (BDI) is the most serious complication of laparoscopic cholecystectomy and occurs i...'
Answer length: 577
Final answer: 'Bile duct injury (BDI) is the most serious complication of laparoscopic cholecystectomy and occurs i...'

Processing question 30/30: How are the cystic duct and artery managed once th...
Retrieved 5 items
Total context chars: 5876
Types: ['text', 'video', 'text', 'text', 'text']
System prompt length: 1032
Full prompt length: 7047
Context items: 5 (4 text, 1 video)
Prompt preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoni...
Input token length: 1536
Generated token length: 1664
Raw output length: 7596
Raw output preview:
Based on the following text and video context items, please answer the query.
Give yourself room to think by extracting relevant passages from the context before answering.
Do NOT reveal your reasoning; output only the answer in an explanatory style.

Example 1:
Query: What is the most serious comp...
Answer after prompt removal: 'Once the critical view of safety is established, the cystic artery is clipped and divided. The cysti...'
Answer length: 548
Final answer: 'Once the critical view of safety is established, the cystic artery is clipped and divided. The cysti...'

,BLEU,ROUGE-L_F1,BERTScore_F1,FactCC_acc,FactCC_conf,Entailment_avg,per_query,GPT_Prec@5,GPT_Faith,GPT_Fluency,GPT_Coherence,combo,per_query_json
5,0.012418,0.106225,0.828812,0.233333,0.293843,0.050377,"{'bert_f1': [0.810492753982544, 0.857899129390...",0.100000,0.566667,3.700000,3.800000,base_retr-none_rerank-fine_gen,"{""bert_f1"": [0.810492753982544, 0.857899129390..."
4,0.012418,0.106225,0.828812,0.233333,0.293843,0.050377,"{'bert_f1': [0.810492753982544, 0.857899129390...",0.133333,0.533333,3.733333,3.833333,base_retr-none_rerank-base_gen,"{""bert_f1"": [0.810492753982544, 0.857899129390..."
8,0.015026,0.098573,0.829545,0.400000,0.446125,0.008455,"{'bert_f1': [0.810492753982544, 0.855551362037...",0.100000,0.533333,3.700000,3.900000,fine_retr-none_rerank-base_gen,"{""bert_f1"": [0.810492753982544, 0.855551362037..."
9,0.015026,0.098573,0.829545,0.400000,0.446125,0.008455,"{'bert_f1': [0.810492753982544, 0.855551362037...",0.100000,0.500000,3.766667,3.833333,fine_retr-none_rerank-fine_gen,"{""bert_f1"": [0.810492753982544, 0.855551362037..."
10,0.011813,0.108823,0.832765,0.333333,0.370119,0.065469,"{'bert_f1': [0.8093953728675842, 0.83539170026...",0.166667,0.500000,3.833333,3.766667,fine_retr-cross_rerank-base_gen,"{""bert_f1"": [0.8093953728675842, 0.83539170026..."
11,0.011813,0.108823,0.832765,0.333333,0.370119,0.065469,"{'bert_f1': [0.8093953728675842, 0.83539170026...",0.166667,0.500000,3.833333,3.800000,fine_retr-cross_rerank-fine_gen,"{""bert_f1"": [0.8093953728675842, 0.83539170026..."
7,0.007090,0.106725,0.829234,0.333333,0.361239,0.053560,"{'bert_f1': [0.8021681904792786, 0.83915650844...",0.133333,0.466667,3.733333,3.800000,base_retr-cross_rerank-fine_gen,"{""bert_f1"": [0.8021681904792786, 0.83915650844..."
6,0.007090,0.106725,0.829234,0.333333,0.361239,0.053560,"{'bert_f1': [0.8021681904792786, 0.83915650844...",0.133333,0.466667,3.733333,3.766667,base_retr-cross_rerank-base_gen,"{""bert_f1"": [0.8021681904792786, 0.83915650844..."
1,0.015818,0.110318,0.828781,0.500000,0.499172,0.036364,"{'bert_f1': [0.8125889301300049, 0.85431641340...",0.033333,0.400000,3.766667,3.800000,random_retr-none_rerank-fine_gen,"{""bert_f1"": [0.8125889301300049, 0.85431641340..."
0,0.013935,0.115094,0.839706,0.433333,0.457728,0.058136,"{'bert_f1': [0.8430566191673279, 0.85475862026...",0.000000,0.400000,4.066667,4.200000,random_retr-none_rerank-base_gen,"{""bert_f1"": [0.8430566191673279, 0.85475862026..."
3,0.017527,0.115757,0.831346,0.300000,0.316426,0.042224,"{'bert_f1': [0.8162652254104614, 0.84201997518...",0.000000,0.366667,3.833333,3.833333,random_retr-cross_rerank-fine_gen,"{""bert_f1"": [0.8162652254104614, 0.84201997518..."
2,0.015215,0.114638,0.832167,0.500000,0.503159,0.048787,"{'bert_f1': [0.8013496994972229, 0.85542887449...",0.000000,0.366667,3.766667,3.666667,random_retr-cross_rerank-base_gen,"{""bert_f1"": [0.8013496994972229, 0.85542887449..."

Index size: 19
Corpus size: 19
Match: True